### ISSUE TITLE
Configure keys interception for remote session

### ISSUE THREAD

**Issue by alishchytovych** [VShawn/PRemoteM#106]
Playing music on the host (for example, via VLC), I want to use keyboard's multimedia keys (start/stop, prev, next track etc.) while working in RDP in the fullscreen mode.  Now all the keys are sent to RDP, so I need to switch back to the host to manage the player. 

It would be great to have he configuration option to exclude some keys / key codes from to be sent into the remote session (RDP etc.). This settings can be global or per session.

**Comment by majkinetor** [comment]
Duplicate of #40 

In short, while the idea is great, we don't know how to do it or is it possible at all.
