### ISSUE TITLE
Connection tags

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#107]
**Is your feature request related to a problem? Please describe.**

Add arbitrary number of tags on any connections which can further improve selection, grouping and categorization, along with providing more operation options

**Describe the solution you'd like**

- Tags should be added in connection config common section and must be set on selected connections via bulk edit
- Tags are shown only in list view either as another column or as second raw in connecton item
- List of tags could be shown in sidebar; clicking on tag would select all connections in current group having it; search could have shortcut via #tag_name
- In launcher #tag_name shows only tagged connections (thinking more about this, perhaps it was better to have special prefix for including group name when searching rather then having it as an option now, for example !group_name).

**Additional context**

Tag would allow arbitrary grouping of connections and allow connection to exist in multiple "groups" (we would still have groups, but those are categories as connection can have only 1). With operations allowed on tags as it were connection, one would also use it to speed up certain actions:

1. Connect to multiple connections as single step
2. Categorization of connections with tags like #db #app #personal #linux #windows etc. Then to see all your windows database servers you would go #windows #db
3. It can basically serve as saved search/cherry pick of connection for whatever purpose; you could as an example mass edit #windows #db and change username for all in one step or export them to format for sharing with others.

From implementation standpoint this is mostly trivial:

1. Add single edit control in configuration that has autocomplete
2. Tags are created as they are written and deleted automatically if they do not have associated connections any more (for example by removing tag or deleting connection)
3. There are 2 new tables, one for tags, other for tag-connections associations
4. In list view, tags are listed in "second row" of the connection item or in new column 
5. There is also collapsable sidebar that lists all tags and few options
    - filtering tag names, sorting tags (by name, usage date or connection number)
    - right click on tag to bring tag and connection options (note: current group applies)
        - tag options: rename, remove
        - connection options: connect all (maybe delete all, duplicate all etc)
    - left click on tag to show only connections with that tag
6. Implement also search via #tag_name as alternative keyboard oriented mechanism

**Comment by VShawn** [comment]
I‘m still hesitating whether to add a tag system. The tag system will make the whole system more complex. And I don’t know where to display the tags and where to place a button to open connections by the tag.

For me I'd like to enable a server to have multiple group names and bulk connect by the group name. This is more intuitive I think.

To achieve this, a lot of things needs to be changed:

- UI
   - server editor needs to support multi-group input
   - in list view right click group name pop a menu with a button ‘open connect’
   - in the launcher enable list group as an individual item (means chuange of control's template and view modle)
- Logic
   - search by groupname 
- Database
   - make the data structure support multiple group names

**Comment by majkinetor** [comment]
This is exactly the same, you just call "tags" by name "groups".  You need to find a way to display many groups. With this functionality, people will use them much more so tabs will not suffice any more. 

We definitely don't need both, and groups are lacking. So IMO, groups should be removed, that is, renamed to tags, and new UI for tags should be implemented. Sidebar with sorted tags does seem like a logical solution. It could have option like "favorite" to move a tag to topmost sidebar section. 

Regarding tags in list view, maybe something like:

![image](https://user-images.githubusercontent.com/85767/119038002-edcec380-b9b2-11eb-9e2d-e21303c7f393.png)

1. Left click a tag name shows only tagged items (so it behaves like a group)
2. Right click on tag could provide some options like _rename tag_, _delete tag_ etc.
3. You can see all tags by clicking Tags tab (next to All since groups are removed).  There you could filter out tags and click on them to show items

Implementation side 
- Database: you would just need 2 tables - Tags and TagsConnections (for association).
- Logic: trivial - CRUD on TagsConnections and Tags
- UI 
    - implement tag control that can be reused on different places (connection list, connection editor, tag list)
    - implement tag editor to be used instead Group name in connection editor
    - add one page that lists and filters tags <details>such as this 
![image](https://user-images.githubusercontent.com/85767/119039402-844fb480-b9b4-11eb-9c6d-d74902edbb1a.png)
</details>

So, for example, to later bulk connect, you will select all desired connections, choose edit, **add tag**, save. Later, click tag, select all, connect. 

One minor problem here is that operations add/set/remove tags can not be done in current editor even with latest changes. It could be used only to set the same tags to all items, but we would need an option to _add tag_ or _remove tag_ from selected connections without affecting other existing tags on those connections.

**Comment by majkinetor** [comment]
Some problems:

- Tags should not be case sensitive IMO
- Tag rename within Tags tab has strange text on init<details><summary>detalji</summary> 
![image](https://user-images.githubusercontent.com/85767/121488197-24f12d00-c9d3-11eb-8b33-c4448ee951c7.png)</details>
- Clicking on tag should work and show items it contains. Now if tag isn't shown as tab, you have no way to select only items that contain it. Click on it should show just those items and probably add in search filed something like `tag:"my tag"` that can be easily cleared to show all items again. Some other interface might be better. <details><summary>detalji</summary> 
![image](https://user-images.githubusercontent.com/85767/121512070-9f2cac00-c9e9-11eb-85cc-7360f0887ade.png)
</details> For example this one keeps tags in a top bar and you have [x] to clear them from the filter
- Tags should not be shown as tabs by default IMO, or better, this should be configurable, what one wants depends on how many tags they plan to use
- Tags should be sorted when displayed

**Comment by VShawn** [comment]
> Tags should not be case sensitive IMO

i don't think so - [capitonym](https://en.wikipedia.org/wiki/Capitonym)

> Tags should be sorted when displayed

i think it is sorted now: sort by first letter. Where do you mean there is no sorting? If you mean custom sorting, well, there is no time for me to implement it : (.

> improvement

some of the improvements have been considered, but since it takes me a lot of time to build the UI, I plan to take it slowly, launching this available version first, and then iterating and upgrading.


---

i will fix the bugs first.

**Comment by majkinetor** [comment]
Tags on item should IMO be sorted, currently they appear in the order of input.
Regarding capitonym, you found very unlikely problem with it. The same objection applies to more fundamental things like windows file system case insensitivity.

**Comment by majkinetor** [comment]
Other thing being pretty good, I think the major thing that needs to be redone is tag editor. It currently has the following problem:

1. Automating switching from view to edit mode and vice versa is districting, especially with what looks is like 2s timer.
2. It should use autocomplete instead [+] button or along with it
3. You can make empty tags in view (not really makde) <details><summary>detalji</summary> 
![image](https://user-images.githubusercontent.com/85767/121788374-11111b00-cbcd-11eb-8208-2bdc5c40f8eb.png)
</details>
