### ISSUE TITLE
Vnc listener

### ISSUE THREAD

**Issue by BGDonLINE** [VShawn/PRemoteM#111]
Thanks for so great project, I was curious is there any chance for vnc listener?

**Comment by VShawn** [comment]
our vnc client was based on archived  project VncSharp(https://github.com/humphd/VncSharp) which is old and not offering a listening mode. And we can't find an alternative now. So vnc listener will unfortunately not be developed in the short term. 

but this ticket will on hold in the limbo, in case we will develop it in the future.
