### ISSUE TITLE
SSH error

### ISSUE THREAD

**Issue by jimmyice** [VShawn/PRemoteM#117]
SSH connection problem encountered

- OS: [chs Win10 Pro for Workstations 20H2]

- PRemoteM Version [ 0.5.10.2]

![1](https://user-images.githubusercontent.com/54651564/116560101-a618c700-a933-11eb-8fb8-d401068bc90a.png)
![2](https://user-images.githubusercontent.com/54651564/116560119-aadd7b00-a933-11eb-932d-e39e80bb0a5b.png)

**Comment by VShawn** [comment]
Strange thing, I remember  I did use the kitty downloaded from the official website, I don’t know why it was considered as a wrong signature. anyway I will upgrade to the latest version of KITTY later, so stay tuned.

---

奇怪，没记错的话我的确用的是官网下载的 kitty，不知为何会被认为签名错误。稍后我会升级到KITTY的最新版本，敬请期待。

**Comment by VShawn** [comment]
@jimmyice 您好，麻烦尝试使用这个测试版本，里面的SSH客户端已升级到KITTY的最新官方版本。

[Release.zip](https://github.com/VShawn/PRemoteM/files/6427077/Release.zip)

**Comment by jimmyice** [comment]
非常的NICE！域名和IP连接都OK

**Comment by VShawn** [comment]
@jimmyice 您好，请问您当初出现这个问题时，使用的是微软商店版本么？

**Comment by jimmyice** [comment]
是的 yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "VShawn/PRemoteM"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月20日(星期四) 下午4:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [VShawn/PRemoteM] SSH error (#117)





 
@jimmyice 您好，请问您当初出现这个问题时，使用的是微软商店版本么？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
