### ISSUE TITLE
Bug in resolution of large-screen display

### ISSUE THREAD

**Issue by zmb4973992** [VShawn/PRemoteM#118]
Dear developer, hello!
I really like the product you developed, but I found a bug:

My monitor is 34 inches with a resolution of 3440 * 1440.When connecting to other computers remotely through PremoteM, it cannot be displayed in full screen. There will be drag bars on the right side and the bottom side. You cannot eliminate these two drag bars. 

You can refer to the screenshot for the specific phenomenon. At high resolution, the drag-and-drop bars appear on the right and below.

If you decrease the resolution, for example, 1440 * 900, this problem goes away. So it is generally assumed that the software is not compatible with high resolution monitors. Can you fix this bug?

Thanks again for the software you developed! 

亲爱的开发者，您好！
非常喜欢您开发的这个产品，但是发现一个漏洞：
我的显示器是34英寸的，分辨率是3440 × 1440。通过软件远程连接到其他电脑时，无法全屏显示，在右侧和下方会有拖拽栏，无法消除这两个拖拽栏。
具体的现象您可以参考截图。在高分辨率的时候，右侧和下方会显示拖拽栏。
如果把分辨率降低，比如1440 × 900，这个问题就没有了。所以大致估计是软件对高分辨率的显示器不能兼容，是否可以修正这个漏洞呢？
再次感谢您开发的软件！已经标星！

![Snipaste_2021-05-02_12-15-35](https://user-images.githubusercontent.com/25313677/116802166-5c9ec680-ab43-11eb-8c09-fa80bfe7158a.png)

**Comment by VShawn** [comment]
应该是分辨率感知有问题，但在我的4k显示器上无法复现这个现象。请问你的显示器缩放设置是多少？另外在窗体模式下改变窗体尺寸，远程桌面的自适应分辨率调整是否正常？

如果可以的话，麻烦操作一轮先全屏，再变为窗口化，再改变窗口尺寸，再全屏的动作，然后把软件的日志发给我分析一下。

**Comment by zmb4973992** [comment]
你好，经过多次测试，发现确实是缩放影响了软件窗体的尺寸。
缩放选择175%时，分辨率为3440×1440和分辨率为2560*1440的显示器都复现了这个问题。
分辨率调整为150%、174%、176%、200%，都不再有这个问题。

另外请问日志的位置在哪？如果还需要的话，我可以提供日志。
谢谢你的辛苦开发！非常感谢！: )

**Comment by VShawn** [comment]
很神奇啊，只有175％的时候分辨率感知出错，而我测试的时候正好只测试了150和200的缩放，没有试过175的。日志暂时不需要提供了，我明天先自己进行175缩放测试，如若不能复现bug再麻烦你传日志进行分析。

**Comment by VShawn** [comment]
很遗憾，无法在我的显示器上复现这个bug。

![image](https://user-images.githubusercontent.com/10143738/116834646-9f1edc80-abf1-11eb-9255-393c9b80d50a.png)

**Comment by zmb4973992** [comment]
或许你可以将显示器的分辨率调整为3440x1440、2560x1600，同时修改缩放比例为175%试试。
我的两个显示器就是上面的参数，都完美复现了这个bug。

刚才我在3440x1440、225%缩放比例下，又复现了这个bug。感觉这些数值之间有某种神秘联系！


解决这个bug的临时方法，大概就是避免使用175%、225%这个缩放比例，其他比例没有发现问题。

**Comment by VShawn** [comment]
@zmb4973992  我始终无法在自己的电脑上复现这个bug，可否劳烦你按以下操作顺序复现BUG后，反馈一下软件日志？

> 先全屏，再变为窗口化，再改变窗口尺寸，再全屏的动作

软件日志位于  `C:\Users\*你的用户名*\AppData\Roaming\PRemoteM` 中，只需要发送当天的日志即可。

请用这个压缩包里的软件进行操作，这个压缩包里增加了显示分辨率的日志记录，感谢您的协助。

[Release.zip](https://github.com/VShawn/PRemoteM/files/6427024/Release.zip)

**Comment by zmb4973992** [comment]
bug在175%缩放比例下已复现，日志附后，请查看。

由于内容太多，日志已上传到网盘，地址是：
https://wwi.lanzous.com/isvfyoxnykj

感谢您的开发！

**Comment by VShawn** [comment]
@zmb4973992 感谢您的支持，不过您似乎没有使用我上传的新版本进行复现测试，因为我没有在日志中看到分辨率相关的记录，例如


```
2021-05-09T00:56:19.3758333+08:00[ThreadId:0000000001]		Debug		RDP Host: init Display with ScaleFactor = 150, W = 2202.66666666667, H = 1178.33333333333

2021-05-09T00:56:19.3768337+08:00[ThreadId:0000000001]		Debug		RDP Host: Display init as RDP.DesktopWidth = 3304, RDP.DesktopWidth = 3304,

```

这些记录只有在我上传调试版本里面才有，您上传的日志就没法分析分辨率是否计算错误了。


能麻烦你下载下面连接的程序，再测试一遍吗？

https://github.com/VShawn/PRemoteM/files/6427024/Release.zip

**Comment by zmb4973992** [comment]
你好，之前的日志已经是基于调试版本的软件了。
我已将原软件卸载、roaming下的内容清空，重新使用调试版本又测试了一次，日志记录如下，供参考。
https://wwi.lanzous.com/i7h3foy7tod

**Comment by VShawn** [comment]
感谢，这次的日志是正确的。不过很遗憾，这份日志显示程序在计算分辨率时得到的是正确的结果，所以依然没能查出BUG的产生原因。

**Comment by zmb4973992** [comment]
那是否需要提供视频？好像没法提供其他更多的信息了。
辛苦了！


Mr. Zhou
 
From: VShawn
Date: 2021-05-10 10:00
To: VShawn/PRemoteM
CC: zmb4973992; Mention
Subject: Re: [VShawn/PRemoteM] Bug in resolution of large-screen display (#118)
感谢，这次的日志是正确的。不过很遗憾，这份日志显示程序在计算分辨率时得到的是正确的结果，所以依然没能查出BUG的产生原因。

**Comment by VShawn** [comment]
视频没有必要，经过这几天的测试我任然没能复现问题。只能暂时把这个 issue 搁置，等待有能力编写C#代码同时能够复现这个BUG的人出现了。

**Comment by VShawn** [comment]
@zmb4973992  期待楼主学会 C# 然后回头帮我 debug /狗头

**Comment by zmb4973992** [comment]
还是感谢你，虽然有点微bug，但还是让大家用上了这么趁手的工具！



Mr. Zhou
 
From: VShawn
Date: 2021-05-20 19:19
To: VShawn/PRemoteM
CC: zmb4973992; Mention
Subject: Re: [VShawn/PRemoteM] Bug in resolution of large-screen display (#118)
@zmb4973992 期待楼主学会 C# 然后回头帮我 debug /狗头
