### ISSUE TITLE
Start Automatically at OS Startup not changing anything

### ISSUE THREAD

**Issue by jrbdog** [VShawn/PRemoteM#119]
**Describe the bug**
I have not enabled "Start Automatically at OS Startup", yet it still automatically starts. PRemoteM is still enabled under Windows 10's Startup menu in the Task Manager.

**To Reproduce**
1. Disable "Start Automatically at OS Startup
2. Close PRemoteM
3. Restart Windows 10

**Expected behavior**
I expected PRemoteM to not autostart and for it to be disabled in the task manager startup settings.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 20H2 19042.928
 - PRemoteM Version: 0.5.10.2

**Additional context**
I installed PRemoteM from the Microsoft Store.

**Comment by VShawn** [comment]
bug confirm, thanks for reporting

**Comment by VShawn** [comment]
https://github.com/VShawn/PRemoteM/blob/dev/PRM.Core/Utils/SetSelfStartingHelper.cs#L230-L241

I found this code doesn’t work under Net Framework,  I tested it under Net core 3.1.

For now, we’ll just have to let the user disable the startup from the task manager
