### ISSUE TITLE
proxy definition

### ISSUE THREAD

**Issue by MatjazMocnik** [VShawn/PRemoteM#12]
I cannot connect to RDP at work, because I cannot define proxy server..
I attached where can I define proxy in standar RDP program (mstsc.exe).
Sorry it's in Slovene, but it is clearly visible :). 
![2020-07-30 06_38_22-PRemoteM](https://user-images.githubusercontent.com/2148856/88881321-67809f80-d22f-11ea-8a7a-58248660445d.png)

**Comment by VShawn** [comment]
WIP #13

**Comment by VShawn** [comment]
Hi Mr/Miss @MatjazMocnik, I have build new version app which is support RD Gateway. Unfortunately I dont have a RD Gateway testing environment, so I am not sure it is work or not. Could you please give a hand for test the new RD Gateway feature?
![Snipaste_2020-08-01_16-07-55](https://user-images.githubusercontent.com/10143738/89097623-1a5d2300-d413-11ea-847b-c35c5036587f.jpg)


Here is the new app:
[PRemoteM 0.4.8.2008011601.zip](https://github.com/VShawn/PRemoteM/files/5010006/PRemoteM.0.4.8.2008011601.zip)

**Comment by GeorgiKarapetrov** [comment]
This is very nice but RD Gateway does not work for me on either PRemoteM.0.4.8.2008191013 or 0.5.1.2011110905

![image](https://user-images.githubusercontent.com/47497662/98916706-25c0ef80-24d4-11eb-80e8-f99403f2905d.png)

Can I get some log for you or turn on some debug parameter?

**Comment by VShawn** [comment]
@GeorgiKarapetrov 

You are so helpful. but RD gateway is a buildin parameter of MSTSCLib, so it's no log for it, the only way to debug is to try to use  RD Gateway in a real environment.

I have tried to build a RD Gateway service in virtual machines but failed. 

So could you help me test these builds, I tell me which one would work.

please make sure you select 'Use these RD Gateway server settings'
![Snipaste_2020-11-14_11-58-26](https://user-images.githubusercontent.com/10143738/99139093-d8c65000-2670-11eb-90b1-4a1deb6553d2.jpg)



Thank you so much
Shawn

[Releases.zip](https://github.com/VShawn/PRemoteM/files/5540170/Releases.zip)

**Comment by GeorgiKarapetrov** [comment]
I am using custom gateway setting, thanks for the tip.
![Capture](https://user-images.githubusercontent.com/47497662/99419350-b2204780-2904-11eb-800c-71008c5f118a.JPG)

Unfotunettly none of the three releases work.

The error is always the same.
![image](https://user-images.githubusercontent.com/47497662/99419151-75545080-2904-11eb-94a7-dace21b14a5d.png)

**Comment by VShawn** [comment]
@GeorgiKarapetrov Bad news, i have no idea what to do now.

**Comment by Shooshka** [comment]
Just FYI, all my RDP's that using gateway works at this moment in PRemoteM.

**Comment by VShawn** [comment]
@Shooshka Thx for feedback. Your message helps a lot, i don't really have much time to build a RD gateway environment. 
Let me know if you have any other questions. 
NRN
