### ISSUE TITLE
Option to show passwords

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#121]
**Is your enhancement related to a problem? Please describe.**
I can not copy password.

**Describe the solution you'd like**
Instead of lock button that needs to be kept pressed, provide checkbox _Show password_ that always resets after closing the editor. Copy should be also possible when password is shown.

**Comment by VShawn** [comment]
you can copy password here at current version. 
![image](https://user-images.githubusercontent.com/10143738/117905269-7e4b3b00-b305-11eb-858b-60cfe28f81df.png)

the password textbox of current version was made by myself, it is not easy to use, so I intend to improt some ui libiary like
https://github.com/MaterialDesignInXAML/MaterialDesignInXamlToolkit
https://github.com/HandyOrg/HandyControl
