### ISSUE TITLE
Run automatically at OS startup even if the checkbox is unchecked

### ISSUE THREAD

**Issue by itagagaki** [VShawn/PRemoteM#122]
Even if the check box Options > General > Startup > "Run automatically at OS startup" is unchecked, 
the program is launched when the OS starts.

OS: Windows 10 Pro 20H2 x64
Version: 0.5.10.2

**Comment by VShawn** [comment]
hi, if you are using microsoft sotre version, it is related to ticket #119, and will be fixed on next publish.

if you are using exe version, then it is a new bug.

**Comment by itagagaki** [comment]
Oh sorry, it is  Microsoft Store version. Then this issue is closed.
