### ISSUE TITLE
Malwarebytes flagges PREMOTEM.EXE as a Trojan.Crypt

### ISSUE THREAD

**Issue by lbrunkho** [VShawn/PRemoteM#123]
Malwarebytes flags PREMOTEM.EXE as a Trojan.Crypt in both the .7z archive and extracted.

**To Reproduce**
1. Download latest release version from GitHub (https://github.com/VShawn/PRemoteM/releases/download/0.5.10.2/0.5.10.2.7z)
2. Scan with Malwarebytes 

**Expected behavior**
Files would pass MBAM scanning so as to not get automatically removed from the system.

**Screenshots**
![image](https://user-images.githubusercontent.com/24943712/118531226-753ddd80-b6fa-11eb-9472-9f4a6a9c560b.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 10 Pro, 10.0.19042 Build 19042
 - PRemoteM Version 0.5.10.2

**Comment by VShawn** [comment]
Hi thanks to reporting the issue. And I'm sorry that I am not a security engineer, so I don't know how to deal with such virus detection problems. Before anyone can help solve it, it is recommended that you include PRemoteM.exe into your virus detection whitelist, or maybe try the Microsoft store version.

**Comment by VShawn** [comment]
I guess it may be because the exe version is not signed, and I added a registry entry for the software to start automatically, or wrote the registry for the Kitty configuration, which caused it to be detected as a virus.

**Comment by lbrunkho** [comment]
Thanks for taking a look into it. I'm going to try add it to the white list on Malwarebytes. Having a signed exe would definitely be nice but I understand this is a lot of work. Also would it be possible to move the Kitty executable out of the main binary?

**Comment by majkinetor** [comment]
> Also would it be possible to move the Kitty executable out of the main binary?

Yes its possible to have 2 variants - light without any dependency and full. On chocolatey at least you would then install it fully with `cinst kitty premotem`. PRM would need to support using kitty from the system (adding options in configuration to specify path if its not on the PATH, or if it is, just use it [as with chocolatey install]).

This obviously requires some work but release could be automated within #79 eventually.

**Comment by majkinetor** [comment]
> Having a signed exe would definitely be nice but I understand this is a lot of work.

I think this is not an option really.

**Comment by VShawn** [comment]
Eventually I make some change by following this approach: https://stackoverflow.com/a/41272682/8629624

and It is no longer detected as a virus in GMail(still be blocked since it is .exe), Don't know if it will be detected as a virus by Malwarebytes.

![image](https://user-images.githubusercontent.com/10143738/119937826-072ccc80-bfbe-11eb-92bc-bcf53ec23a07.png)

**Comment by majkinetor** [comment]
I wouldn't be concerned at all, it is what it is. No other scanner detects it:

- https://www.virustotal.com/gui/file/b2be1823763ee11ac973d4b94281340289de90f17b9a82236487598e00517d33/detection/f-b2be1823763ee11ac973d4b94281340289de90f17b9a82236487598e00517d33-1617487986

**Comment by lbrunkho** [comment]
Thanks for all the work @majkinetor and @VShawn! I am going to add this to the Malwarebytes exception list and move on. I would like to take a look at a lite release when/if that happens and see if it still gets flagged. This ticket can be closed. Again thanks for your time!
