### ISSUE TITLE
It is recommended that RDP connection do not use the credentials saved by Windows system to connect, and add RDP security option

### ISSUE THREAD

**Issue by dongyi945** [VShawn/PRemoteM#126]
在使用该软件时发现，添加RDP服务器后，如果windows保存了登录凭据，RDP配置中的用户名和密码不起作用，软件会自动使用windows保存的登录凭据进行认证。只有从windows中删除保存的登录凭据后，才使用RDP配置中的用户名和密码进行连接。
另外无法设置RDP安全协议，如选择使用SSL、RDP、或者协商。

When using the software, it is found that after adding the RDP server, if windows saves the login credentials, the user name and password in the RDP configuration will not work, and the software will automatically use the login credentials saved by windows for authentication. Only after deleting the saved login credentials from windows can you connect using the user name and password in the RDP configuration.
In addition, RDP security protocol cannot be set, such as SSL, RDP, or negotiation.

**Comment by majkinetor** [comment]
Seems like another case similar to #125 where random connection / clean is discussed.

**Comment by VShawn** [comment]
@dongyi945 

1. Thanks for the feedback, we already know the problem you mentioned, but we are still trying to solve it.
2. How to set the RDP security protocol through mstsc.exe? I did not find where to config it.

1.  感谢反馈，您提到的问题我们已经知道了，但仍然在尝试如何解决它。
2.  请问该如何通过 mstsc 设置RDP安全协议？我没找到在哪设置。

**Comment by VShawn** [comment]
close this ticket since #125 is colsed
