### ISSUE TITLE
Default credential

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#128]
**Is your enhancement related to a problem? Please describe.**
If connection doesn't fully specify credential, use default one. 

**Describe the solution you'd like**
In global configuration add option _Default credential_ that accepts username, password and key. User can fill in any of those fields and they are used for missing connection fields.

Fields should accept environment variables, for example `%USERDOMAIN%\%USERNAME%` .

**Comment by bluikko** [comment]
As a side note - it would be nice to have one setting (registry value, so that it can be set with group policy) for disabling saving all passwords.

**Comment by VShawn** [comment]
this is much beyond `personal remote manager` purpose.

**Comment by majkinetor** [comment]
Agree, if you mean on @bluikko comment.

**Note**: with groups one could specify default credential within a group (this is like on mRemoteNG but it doesn't work there due to bug). However, if groups are removed and tags are implemented instead (#107) it becomes harder since you can have multiple tags.  I don't think this option is THAT valuable tho, having 1 default should be enough for 99.9% of users)

**Comment by VShawn** [comment]
since we have the bulk edit, Do we still need this feature?

**Comment by majkinetor** [comment]
Its way less needed with bulk edit. It still provides some convenience but now its minimal. Its better to keep things simpler so I will close this.
