### ISSUE TITLE
Add ability to edit temporary rdp file

### ISSUE THREAD

**Issue by Kyogre** [VShawn/PRemoteM#129]
When user uses [multiple monitors with different zoom levels](https://github.com/VShawn/PRemoteM/issues/125#issuecomment-845682821) PRemoteM uses mstsc.exe and stores temporary rdp-file in %temp%.
That file has so many settings, but user has no ability to edit it neither **when using PRemoteM**, neither **via PRemoteM itself**.

**Comment by VShawn** [comment]
In fact, all important configurations in rdp-file will be overwritten, only the dispensable settings are not used. I think temporary edit is not necessary for most people.

**Comment by VShawn** [comment]
link to https://github.com/VShawn/PRemoteM/commit/1b279971ebe39ab1e56be2e6411299fcc016eac5

**Comment by VShawn** [comment]
Hi @Kyogre in next version, PRM will allow you to customize rdp file options.

![image](https://user-images.githubusercontent.com/10143738/143599699-00219e83-e44b-41f5-b0f5-729be34b1037.png)


Sorry for the slowly approach, I just too busy on work these days.

**Comment by VShawn** [comment]
@Kyogre, hi, [here](https://github.com/VShawn/PRemoteM/releases/tag/0.6.0-beta) is our new beta release, try it to edit the rdp file template.
