### ISSUE TITLE
Importing mRemote CSV looses Domain

### ISSUE THREAD

**Issue by do5rsw** [VShawn/PRemoteM#136]
I just imported a mRemoteNG CSV that had been exported with all information that can be exported in mremote. It contained about 150 connections and all use not only a rdp user but also da domain name.
Importing this into Premote resulted in all connections loosing the domain and leaving PRemote to try to log in as local user instead. 
There is no domain field in the connection properties as there is in mremote so I guess the importer simply ignored it. 
If there is no domain field the domain shoud be added to the user instead of ignoring it. It has to be <domain>\<user> then. Otherwise that would be useless. I now have a 150 rdps that are missing the domain in the username due to that ...

In most bigger or commercial environments you do have active directory and so you have to use domain user. So I think a fix of this would be very welcome :)

**Comment by majkinetor** [comment]
> There is no domain field

Domain is specified as in Windows login, e.g. `domain\user`.

As a workaround, you can fix it quickly: if you have small number of users you can quickly fix it by doing bulk edit of connections. If not, you can fix it in sql directly .

**Comment by do5rsw** [comment]
@majkinetor: yeah that's what I wrote. Since I use only just one rdp user for all my connections bulk editing in the csv indeed is a workaround or quickfix. I did just that for now.
Still it would be kind if the importer would do that correctly ;)

**Comment by majkinetor** [comment]
Yeah, definitely. Good to know bulk editing worked, it was just done recently :)

**Comment by majkinetor** [comment]
1 RDP user for 150 connections ? That is wild :)

**Comment by do5rsw** [comment]
one admin - 150 Servers :)

**Comment by majkinetor** [comment]
I hope at least password is different :)

**Comment by majkinetor** [comment]
>  bulk editing in the csv

Ah, I hopped you used PRemoteM bulk edit :) You would just select all connections in list view, edit and set user for all.

**Comment by VShawn** [comment]
Arr sorry for the late reply, I didn't get a notification of this ticket, so I just found it today.

As a personal user I did't know how a domain works and I dont have a environment to test demain. that's why I ignored domain in the importer.

I guess set the `Domain` property may fix the ticket? Did we need a password if `Domain` property is set?

![image](https://user-images.githubusercontent.com/10143738/122497799-91e27380-d020-11eb-8ad6-477c9dedaa23.png)

**Comment by majkinetor** [comment]
> Did we need a password if Domain property is set? 

?

> I guess set the Domain property may fix the ticket? 

It looks so.

I can test it in corporate environment

**Comment by do5rsw** [comment]
@VShawn: no problem. The importer should just set username as Domain\Username if _rdp.Domain is not empty. And yes we still ned a password of course :)
There is no need to add a domain field in the connection properties as the above is valid for rdp connections.

@majkinetor: yeah bulk editing inside premote would have workarounded that too ( if I knew that were possible *g*) but bulk editing the csv does the same and is in my case also simpl searh&Replace :)  So don't really matter in this case :)

**Comment by VShawn** [comment]
okey, I add Domain filed for rdp settings. Don't know if it will works

![image](https://user-images.githubusercontent.com/10143738/122626093-10035080-d0db-11eb-80ab-2254343e4d38.png)

[0.5.10.3-beta.2.zip](https://github.com/VShawn/PRemoteM/files/6679741/0.5.10.3-beta.2.zip)

**Comment by stetze88** [comment]
The Domain Field is still empty After import. The loadbalanceinfo field is empty after import too. Maybe a Problem with the inheritance from mRemoteNG? But the username and passwort field works. Mhh...

**Comment by VShawn** [comment]
@stetze88 sorry I haven't finished the import function yet, It still a local brach on my PC. That's why the domain and loadbalanceinfo not work on the beta release. For now, you have to bulk editing the servers' config by yourself.

**Comment by stetze88** [comment]
@VShawn 

Bulk editing works with the identical domain. I also have around 40 servers where I have to log in with the local administrator. Then the domain is always the server name and bulk editing then unfortunately does not work. But then everything is fine and we just have to be patient. 🙂  I love your Software. 😁

**Comment by majkinetor** [comment]
@stetze88, just select those 40 servers in PRM and bulk edit them in application to remove domain (using 0.5.10.3-beta.2.zip).
