### ISSUE TITLE
loadbalanceinfo field for RDP

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#138]
> Support for Windows Server 2016 RDS will be nice.
Yes. 👍🏻 

We need an field for the loadbalanceinfo:s:tsv://MS Terminal Services Plugin.1.<c_collection>

- loadbalanceinfo is the parameter name
- s is the type of value that this parameter expects. "S" means "String". I'm sure that if you look in your RDP file, you will find settings with "i", it means "Integer".
- tsv://MS Terminal Services Plugin.1.<c_collection> is the value of the parameter "loadbalanceinfo", it's a string.
https://serverfault.com/questions/913236/need-explanation-of-tag-loadbalanceinfostsv

_Originally posted by @stetze88 in https://github.com/VShawn/PRemoteM/issues/26#issuecomment-864374219_

**Comment by VShawn** [comment]
@stetze88 can you try this beta version?

![image](https://user-images.githubusercontent.com/10143738/122751206-06880d00-d2c2-11eb-8049-b883d95c357b.png)

[0.5.10.3-beta.2.zip](https://github.com/VShawn/PRemoteM/files/6686113/0.5.10.3-beta.2.zip)

**Comment by stetze88** [comment]
@VShawn 
Unfortunately, it does not work.
![image](https://user-images.githubusercontent.com/73733823/122752588-703bf300-d291-11eb-9fca-f954b9e64b87.png)
![image](https://user-images.githubusercontent.com/73733823/122752639-7fbb3c00-d291-11eb-8c7e-229837ef419d.png)

With mRemoteNG you still have to set this hook
![image](https://user-images.githubusercontent.com/73733823/122753796-0d4b5b80-d293-11eb-8182-78ad89ec5f3e.png)

**Comment by VShawn** [comment]
you don't need send me the log, I'll go and check how mRemoteNG make this. : )

**Comment by VShawn** [comment]
this may help

https://github.com/mRemoteNG/mRemoteNG/blob/2cf5a4317d0cbd61c2135aa8f7ab608db2d88629/mRemoteNG/Connection/Protocol/RDP/AzureLoadBalanceInfoEncoder.cs#L9-L37

**Comment by stetze88** [comment]
Works great. :)
