### ISSUE TITLE
Hide local keyboard input method when guest has focus

### ISSUE THREAD

**Issue by Spicasun** [VShawn/PRemoteM#139]
hope to add a new setting to not hide the local input method

**Comment by majkinetor** [comment]
Maybe this ?

![image](https://user-images.githubusercontent.com/85767/122882966-00834200-d33d-11eb-824c-9057459dbd70.png)

Mhm... this also means that we can actually have host and guest hotkeys at the same time.

**Comment by Spicasun** [comment]
***@***.***D7678B.A3849850]

***@***.***D7678B.CE786230]


In the first picture, the input method is normally displayed when the focus is on the local computer. In the second picture, the input method is hidden when the focus is on the remote window. Sometimes, when the focus returns to the local computer, the input method will not be restored and will always be hidden.

I'm sorry my English level is not good, I use the translation software
发件人: ***@***.***>
发送时间: 2021年6月22日 15:03
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [VShawn/PRemoteM] Related functions of input method (#139)


In RDP?

Can you describe what is "hide the local input method"? I didn't do anything to the input method

―

**Comment by Spicasun** [comment]
![A](https://user-images.githubusercontent.com/86285154/122907061-57146e80-d385-11eb-8d27-001d0b04aff0.png)
![b](https://user-images.githubusercontent.com/86285154/122907068-58de3200-d385-11eb-8b16-1ee71740dc63.png)
In the first picture, the input method is normally displayed when the focus is on the local computer. In the second picture, the input method is hidden when the focus is on the remote window. Sometimes, when the focus returns to the local computer, the input method will not be restored and will always be hidden
.

**Comment by majkinetor** [comment]
Seems nitpicky :) Didn't even know it exists...

**Comment by VShawn** [comment]
I think this error may caused by windows. My Chinese input method works great with remote window.
