### ISSUE TITLE
English language issues

### ISSUE THREAD

**Issue by luki1412** [VShawn/PRemoteM#140]
**Describe the bug**
SSH Version has a typo. In the program it is spelt as SSH Verison.

**To Reproduce**
Open the English language file and find the line:
 "server_editor_advantage_ssh_version": "SSH Verison",

**Screenshot**
![ss](https://user-images.githubusercontent.com/20016096/122932942-76ec6800-d36e-11eb-8002-9fec5f402893.png)

**Comment by majkinetor** [comment]
While we are at it:

### Resize

![image](https://user-images.githubusercontent.com/85767/122992205-27299300-d3a6-11eb-8d51-dc2c64889c5a.png)

## Needs space before parenthesis on multiple places

![image](https://user-images.githubusercontent.com/85767/122992263-37417280-d3a6-11eb-8ab3-2b6558ab618d.png)

![image](https://user-images.githubusercontent.com/85767/122992324-488a7f00-d3a6-11eb-860a-ac3bec5c5c63.png)

![image](https://user-images.githubusercontent.com/85767/122992346-4d4f3300-d3a6-11eb-8f96-8ffc5a790db3.png)

### Small s should be big S

![image](https://user-images.githubusercontent.com/85767/122992423-65bf4d80-d3a6-11eb-8f75-f98e2f31a9b3.png)

### Grammar

![image](https://user-images.githubusercontent.com/85767/122992488-78398700-d3a6-11eb-908a-6f597732e4d3.png)

_YOU should configURE it on THE server side_


![image](https://user-images.githubusercontent.com/85767/122992991-0d3c8000-d3a7-11eb-946a-248137e2f3d4.png)

Include tags within search

### Migrate button

![image](https://user-images.githubusercontent.com/85767/122992804-d5353d00-d3a6-11eb-89ab-ff8f70ead78a.png)

**Comment by VShawn** [comment]
I seems lots of things to do  : )

**Comment by luki1412** [comment]
I dont think its a lot of work, its just a longer list.

That Launcher screenshot shows two checkmark boxes with labels on different sides and that looks awful. They should only be on one side.

Not sure what they meant to change on the Migrate button. Maybe to change it to something like "Export" ?

**Comment by VShawn** [comment]
Yes, I just mean I make los of mistakes on UI. They won't take much time to fix.

---

Migrate button is for someone want to move database to another path.
