### ISSUE TITLE
unable connect linux ssh

### ISSUE THREAD

**Issue by cjdxhjj** [VShawn/PRemoteM#142]
**Describe the bug**
connect to linux ssh not work
**To Reproduce**
1. Click Add "+"
2. Change to Tab SSH
3. Type User And Password, port..
4. Click Save
5. Double Click the marchine item

**Expected behavior**
connected to the ssh shell

**Screenshots**
![image](https://user-images.githubusercontent.com/5616997/123772542-80417b80-d8fe-11eb-8ee8-22d97395e6da.png)
![image](https://user-images.githubusercontent.com/5616997/123771585-be8a6b00-d8fd-11eb-9a6e-2fbe5ddee0ce.png)

**Desktop (please complete the following information):**
 - OS: [Win10 Pro 20H2]
 - PRemoteM Version [0.5.10.2]

**Additional context**

**Comment by majkinetor** [comment]
Duplicate: https://github.com/VShawn/PRemoteM/issues/98
