### ISSUE TITLE
Bulk connect window options

### ISSUE THREAD

**Issue by BrommD** [VShawn/PRemoteM#144]
**Is your feature request related to a problem? Please describe.**
in #107 the option was removed to open connection grouped in own window automatically. Now with "tags" I can open all connection belonging to a tag , but they all are placed in same existing windows (where the handling of such overloaded "tab" windows is quite cumbersome). This is not very comfortable to former version. Rather having 10 windows open with 3-4 grouped connection, than one window with 30-40 tabbed connection.

**Describe the solution you'd like**
Have the possibility to open tagged connection "grouped" into own window (again), in case there are more tags assigned per connection, this option is disabled (as it does not make sense for application to guess to which window to place the new connection), so this will also work using implementation #107. 

**Describe alternatives you've considered**
detaching and moving opened connection (from same group/ag) from main window to separate one, so having multiple windows with their own dedicated connections (i.e. "systems" or "mandator")

**Additional context**

**Comment by majkinetor** [comment]
Since you can use multiple tags, nothing stops you from creating N groups of connections and multi connect to specific group using its tag.

Regarding new/existing window, that is a feature request that is as I see it only possible if you have another option. Now we have button Connect, and we could have button _Connect using single window_, _Connect using multiple windows_.

**Comment by BrommD** [comment]
Right, the upper part (tagging, whatever required) is just fine, only the removed option "open in new windows" is missing here.... I would prefer to have sth default for connection profiles, like this was able in "grouped" feature in old version, but I can also live with "tag/open in new window" processing
thx, Dejan

**Comment by majkinetor** [comment]
OK, so we could have something like this:

[Connect v] button with submenu.  Connect itself triggers default action and both actions are available via drop down menu. Default action is set in the configuration

- [ ] Bulk connect to multiple windows

So default would be as it is now (single window) and if you check that option in global configuration it would become multiple windows by default, but one would still have an option to ad hoc choose both options (as it seems to me this use case is situational).

This is trivial to implement, looks useful, and resolves all the problems you have.

**Comment by BrommD** [comment]
SOLD! :)

**Comment by VShawn** [comment]
What about an option `Connect to new window` to let user choose where the new connection should be placed.

![image](https://user-images.githubusercontent.com/10143738/126028832-2885d478-32b6-420e-b49c-8d8975d276b5.png)

![image](https://user-images.githubusercontent.com/10143738/126028889-7c149f91-00fb-4b1c-adc8-4c82f016eec7.png)

By this option, a new tab window will created and the new connection (sigle connection by click single session / all connections open by a tag) will be placed in this new window.

We don't need a configuration to setup the `Default action for top level Connect is set in the configuration`

**Comment by majkinetor** [comment]
Sounds good

**Comment by BrommD** [comment]
Hi, if it does not create much effort, a configuration possibility would be great. Thx, Dejan

**Comment by majkinetor** [comment]
I initially proposed that because with only 2 options, you need to **always choose**, so each bulk connect is extra mind step. So if you connect to same window 90% of the time, it is more efficient to set default to 'same window' and then override that default when you need it in ad hoc manner.

**Comment by BrommD** [comment]
Hi
just want to add here, that the possibility to open a windows quickly in same or in new windows without using the mouse (press hotkey, type/search, chose profile, cursor-right, chose "new windows" or not) is simply great.

thanks for making this possible.

Dejan

**Comment by VShawn** [comment]
> that the possibility to open a windows quickly in same or in new windows without using the mouse

@BrommD

session open from Alt + M will be opened in same window or  new window, did this not work for you?

![image](https://user-images.githubusercontent.com/10143738/147171040-f53b6d93-6ec7-4bd1-b177-816abbfe5079.png)

**Comment by BrommD** [comment]
hi,  sry, I was not accurate enough. I want to say thx for exactly having implemented such an option. This works great.

Regards, Dejan

Von: VShawn ***@***.***>
Gesendet: Donnerstag, 23. Dezember 2021 01:48
An: VShawn/PRemoteM ***@***.***>
Cc: Bromm, Dejan ***@***.***>; Mention ***@***.***>
Betreff: Re: [VShawn/PRemoteM] Bulk connect window options (#144)


that the possibility to open a windows quickly in same or in new windows without using the mouse

@BrommD<https://protection.retarus.com/v1?u=https%3A%2F%2Fgithub.com%2FBrommD&c=3ilYjgr&r=5In0snLjkrlk42h66QEkX3&k=7s1&s=rcuUjx54e2mvHJlgIYGvZvsqTsadGWaYH88RTX6D9kF>

session open from Alt + M will be opened in same window or new window, did this not work for you?

[image]<https://protection.retarus.com/v1?u=https%3A%2F%2Fuser-images.githubusercontent.com%2F10143738%2F147171040-f53b6d93-6ec7-4bd1-b177-816abbfe5079.png&c=3ilYjgr&r=2sPlC8RAjVHX1XRpemFzRN&k=7s1&s=gTVMWckbrMGVrIiMKweTogKpshcYvhClBmxzXrmWcZm>
