### ISSUE TITLE
Can you add an option to automatically connect SFTP when establishing an SSH connection？

### ISSUE THREAD

**Issue by leesings** [VShawn/PRemoteM#145]
在连接ssh时，同时有上传和下载文件的需求，希望在建立ssh时有个选项可供选择，是否连接时自动打开sftp连接，这样不用每次连服务器时既要配ssh又要配sftp，还要打开连接两次。

When connecting SSH, there is also a need for uploading and downloading the file, I hope that there is an option to choose to select if the SSH is established, it will open the SFTP connection when connecting, so that each of the servers must be equipped with SSH and SFTP, Also open the connection twice.

**Comment by VShawn** [comment]
你好，我一直有考虑这个功能，见 https://github.com/VShawn/PRemoteM/issues/26 中的 `sFTP/FTP with in SSH?`

但我一直没能实现 ssh 和 sftp 的路径同步（即 ssh `cd home` 后，sftp 无法同步进入 home 目录）， 所以一直没放出这个功能。

我已经考虑放弃同步路径的特性，启用这个功能后直接在窗口左右分别显示两个相互独立的 ssh 窗口和 sftp 窗口，不过这个功能我暂时还没空写，目前程序开发以维护、重构为主。



Hi, I‘ve considered this feature for long, see https://github.com/vshawn/premotem/issues/26 in `sftp / ftp with in ssh?`

But I am not been able to sync the path of SSH and SFTP (ie ssh `cd home`, SFTP cannot gose into the home directory automatically), so this feature has not been released.

Ignore the sync of path, we can show two independent SSH on the left side of the window and SFTP on the right side of the window, it is easy to implent.

**Comment by VShawn** [comment]
accturally, I add the option in 0.6.0-alpha, though,  it is hard to use beacuse we dont have `Split Screen`

![image](https://user-images.githubusercontent.com/10143738/132780722-fda7147f-c86d-4a97-95dc-2eb911f4a42f.png)

![image](https://user-images.githubusercontent.com/10143738/132781065-e7387ede-5282-43b7-a34c-f05f768393d3.png)

**Comment by 9raxdev** [comment]
因为ssh 配置已经包含了sftp的大部分信息，可以可以像mremoteng一样，可以自定义几个参数直接启动外部工具如winscp , 在列表处直接选择性调用自己配置的程序

![image](https://user-images.githubusercontent.com/11805413/132937616-cfc9995b-d01f-41bc-a88f-9400ad034dde.png)

**Comment by VShawn** [comment]
it is done in #161
