### ISSUE TITLE
NX as connection option

### ISSUE THREAD

**Issue by Josephkready** [VShawn/PRemoteM#147]
**Describe the solution you'd like**
Having NX (NoMachine) as a connection option. If I have nomachine service installed on a machine, I would like to use PRemoteM to connect to that machine using the NX protocol. 

NX protocol seems to be much faster than xrdp for linux machines. It could be challenging to integrate, so I am interested on what you think.

**Comment by majkinetor** [comment]
Never heard about it.

Here is some quick info for others.

* https://en.wikipedia.org/wiki/NX_technology

**Comment by VShawn** [comment]
Hi I've considered FreeNX protocol when I create the demand planning at 2020.04. 

https://github.com/VShawn/PRemoteM/projects/3#card-38295433

![image](https://user-images.githubusercontent.com/10143738/129499837-8ea74c9d-ea35-46d0-9a5b-05dd563ff108.png)

But afert some investigations, here are some challenges we meet:

## 0. open by command line 

![image](https://user-images.githubusercontent.com/10143738/129502833-c04087da-a544-4f65-902e-0e502e222092.png)

NoMachine client can start connection only by passing a config file to it.

## 1. password storage

In the file `arm.nxs` I didn't see a field storaged the password, but cmd `.\nxplayer.exe D:\arm.nxs` did not request me to enter a password. So we don't know how to genterate a NoMachine config file containing a password by PRemoteM.

## 2. Integer

 cmd `.\nxplayer.exe D:\arm.nxs` will start a process A, then A will exit and start new process B (not a sub-process of process A) to show the remote desk window.

Then PRemoteM can not capture the PID of  process B, which means we cannot integer NoMachine client window into the tab window of PRemoteM.




===

I still looking for the solutions for these challenges, no progress yet.

**Comment by VShawn** [comment]
merged into main branch #161

**Comment by VShawn** [comment]
@Josephkready hi, [here](https://github.com/VShawn/PRemoteM/releases/tag/0.6.0-beta) is our new beta release, you can try it with NX
