### ISSUE TITLE
0.5.11.1 Portable: Does not start at all

### ISSUE THREAD

**Issue by valsamis-d** [VShawn/PRemoteM#150]
**Describe the bug**
After "installing" the portable version (0.5.11.1) and double-clicking the "exe" file, PRemoteM does not start at all. 

**To Reproduce**
1. Completely delete previous version from portable directory (E:\PApps\PRemoteMPortable)
2. Extract 0.5.11.1 portable version to portable directory
3. Double click "P:\PApps\PRemoteMPortable\PRemoteM.exe"
4. Nothing happens

**Expected behavior**
Initial settings wizard should appear

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise (21H1)
 - PRemoteM Version [e.g. 0.5.11.1]

**Comment by VShawn** [comment]
Have you installed [.NET Framework 4.8](https://dotnet.microsoft.com/download/dotnet-framework/net48)?

We need it as the base environment.

If you installed .NF 4.8. then please send me the log file in the `C:\Users\USER NAME\AppData\Roaming\PRemoteM`, I will check out what happened.

**Comment by valsamis-d** [comment]
I have .NET Framework 4.8 installed.

Emptied "C:\Users\USER NAME\AppData\Roaming\PRemoteM" completely since I was using 0.5.10

"Reinstalled" 0.5.11.1 portable

Executed it and didn't start at all. Also no files were found in "C:\Users\USER NAME\AppData\Roaming\PRemoteM"

**Comment by majkinetor** [comment]
Empty event viewer, then start the app, then look into it and give errors.

**Comment by valsamis-d** [comment]
Cleared "Application" logs in event viewer and started the portable version of PRemoteM. Some entries were logged in "Application" logs. See attached. The 1000 Event ID is translated in English as:

```
Faulting application name: PRemoteM.exe, version: 1.0.0.0, time stamp: 0xac8a04e2
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1202, time stamp: 0x448a4f5d
Exception code: 0xe0434352
Fault offset: 0x0012b5b2
Faulting process id: 0x7ef8
Faulting application start time: 0x01d7a34f8b7d80c3
Faulting application path: P:\PApps\PRemoteMPortable\PRemoteM.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 371ec904-30aa-4962-8bc4-1e20b9342b2b
Faulting package full name: 
Faulting package-relative application ID: 
```

_
[PRemoteM_Application_Logs.zip](https://github.com/VShawn/PRemoteM/files/7117546/PRemoteM_Application_Logs.zip)
_

**Comment by majkinetor** [comment]
0xe0434352 is the code for a CLR (.Net runtime) exception. I opened your event viewer log and this is in it:

```
Application: PRemoteM.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotSupportedException
   at System.Reflection.RuntimeAssembly.nLoadFile(System.String, System.Security.Policy.Evidence)
   at System.Reflection.Assembly.LoadFile(System.String)
   at VariableKeywordMatcher.Builder.LoadProviders()
   at VariableKeywordMatcher.Builder.Build(System.Collections.Generic.IEnumerable`1<System.String>, Boolean)
   at PRM.Core.Model.KeywordMatchService..ctor()
   at PRM.Core.Model.PrmContext..ctor()
   at PRM.App..cctor()

Exception Info: System.TypeInitializationException
   at PRM.App.Main()
```

Bug in `KeywordMatchService` seems to cause this

**Comment by valsamis-d** [comment]
Hmmm... This is strange as it seems that I do have .NET 4.8 installed:

**Comment by valsamis-d** [comment]
@VShawn @majkinetor any ideas on why .NET 4.0 is chosen instead of .NET 4.8?

**Comment by VShawn** [comment]
> @VShawn @majkinetor any ideas on why .NET 4.0 is chosen instead of .NET 4.8?

No idea, I have a same .net environment, but eveything work well on me.

![image](https://user-images.githubusercontent.com/10143738/132606517-50b83c6f-7fdb-4ffc-9deb-ce296c6ee2d6.png)

Maybe you can give a try on Microsoft Store version?

**Comment by valsamis-d** [comment]
@VShawn I tested the Microsoft Store version and it starts up normally and without any issue. I noticed, though, that the PRemoteM version is 5.11.**2** and not 5.11.**1** like the portable version I tested. Overall, I prefer to have the portable version working. Thanks for the feedback!

**Comment by VShawn** [comment]
the difference between 5.11.2 is there, nothing special, I dont think it can fix your ticket.
https://github.com/VShawn/PRemoteM/commit/a98df886a280ba206d3b129ace44a53b65a46b3e

---

In case you would like to test here it the portable 0.5.11.2.
[PRemoteM-0.5.11.2.zip](https://github.com/VShawn/PRemoteM/files/7140388/PRemoteM-0.5.11.2.zip)

**Comment by valsamis-d** [comment]
@VShawn it's exactly like you said. This 5
.11.2 version didn't make any difference. Hope you can find any leads why this is not working

**Comment by souchprod** [comment]
Hi, same issue here, .net 4.8 installed, no way to start the exe

**Comment by ikvm** [comment]
@valsamis-d @souchprod  try Updated  application configuration files to enabled loadFromRemoteSources:
<configuration>
   <runtime>
      <loadFromRemoteSources enabled="true"/>
   </runtime>
</configuration>

ref: https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd409252(v=vs.100)?redirectedfrom=MSDN

**Comment by valsamis-d** [comment]
> 
> 
> @valsamis-d @souchprod try Updated application configuration files to enabled loadFromRemoteSources:
> 
> ```
> <configuration>
>    <runtime>
>       <loadFromRemoteSources enabled="true"/>
>    </runtime>
> </configuration>
> ```
> 
> ref: https://docs.microsoft.com/en-us/previous-versions/dotnet/netframework-4.0/dd409252(v=vs.100)?redirectedfrom=MSDN

Thanks for the tip @ikvm !

I'm running the portable version and cannot really find a 'config file' to include the above? Can you please clarify?
