### ISSUE TITLE
Version: 0.5.11.1 still not availible in MS Store

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#151]
In the MS Store the version is still 0.5.10.2. Please update the version.

Thank you.
![Screenshot 2021-09-06 161213](https://user-images.githubusercontent.com/73733823/132230099-5a4b60b4-d14a-4122-bf88-e8e647f60e18.png)
![Screenshot 2021-09-06 161344](https://user-images.githubusercontent.com/73733823/132230227-273c991b-c000-4d30-96fa-a47ece35ac8e.png)

**Comment by VShawn** [comment]
i forgot to update the MS Store. now it should be availabe on ms store now.

**Comment by VShawn** [comment]
something went wrong, I need update it again. 😢

**Comment by VShawn** [comment]
ohhh, finally found that I was in the test user group, so I always get the old version.
