### ISSUE TITLE
本机分辨率1920，想用1600分辨率全屏连接远程桌面，结果显示的仍是1920

### ISSUE THREAD

**Issue by tohghua** [VShawn/PRemoteM#152]
如题

**Comment by VShawn** [comment]
抱歉，全屏模式一开始设计时就定为全屏时RDP会自动恢复到你显示器的分辨率大小。

如果要用固定分辨率，就只能使用窗口模式。

**Comment by tohghua** [comment]
"https://github.com/mRemoteNG/mRemoteNG"是支持的，您可以参考一下
