### ISSUE TITLE
Create an observation field

### ISSUE THREAD

**Issue by profbaco** [VShawn/PRemoteM#154]
Hello, how is everything?
I'm trying again, it doesn't cost anything does it? According to issue #78 I had commented on an observation field in a listing, but to tell the truth, this observation field, in the settings, would be perfect, right on this screen, where I'm sending the print.

![Capturar02](https://user-images.githubusercontent.com/5287317/136028634-da82e42d-f010-40c6-8abd-03348c32c15e.PNG)

We have 6 servers and each one with several different tasks, so when someone asks to upload a certain Windows system service, I have to keep looking in Notepad, which server that service is installed on.
If we had this option in the settings, it would help a lot. He doesn't need this one in the listing, because it doesn't make much sense, but in the settings, yes.
Is there this possibility?

============================================

Olá tudo bem?
Eu estou tentando de novo, não custa nada não é mesmo? De acordo com a issue #78 eu tinha comentado sobre um campo de observação em uma listagem, mas pra falar a verdade, este campo de observação, nas configurações seria perfeito, bem nesta tela, onde estou mando o print.
![Capturar02](https://user-images.githubusercontent.com/5287317/136028634-da82e42d-f010-40c6-8abd-03348c32c15e.PNG)

Estamos com 6 servidores e cada um com várias tarefas diferentes, aí quando alguém pede para subir um determinado serviço do sistema Windows, eu tenho que ficar olhando no Bloco de Notas, em qual servidor aquele serviço está instalado.
Se tivéssemos esta opção nas configurações, já ajudaria bastante. Ele não precisa esta na listagem, pois não faz muito sentido esta lá, mas nas configurações sim.
Existe esta possibilidade?

**Comment by majkinetor** [comment]
I don't see whats new regarding ideas in #78 ?

**Comment by majkinetor** [comment]
BTW, you could also use 1 or more tags for that (e.g. service name). Tags are not that limited in length although current UI doesn't display more then 50 or so chars:

![image](https://user-images.githubusercontent.com/85767/136031441-3d3aa843-655b-4292-9195-62cd556c4838.png)

/cc @VShawn if tag is that big, [x] is out and you can no longer delete it.

**Comment by profbaco** [comment]
Excellent ideas, will solve all my problems. Thanks for the tip.
==========
Excelente ideias, vai resolver todos os meus problemas. Obrigado pela dica.

**Comment by VShawn** [comment]
/cc @VShawn if tag is that big, [x] is out and you can no longer delete it.

arrr...got it.
