### ISSUE TITLE
Check Screen Resolution at startup

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#156]
Can you check the screen resolution at startup?
I use a wqhd monitor at work in window mode.

My notebook has only a fhd display. 
At home i start premotem on this display and its too huge for my screen resolution. 
The menu bar and scrollbars nearly not visible.

Thanks in advance.
Best regards. stetze

**Comment by VShawn** [comment]
I see, I think I know what happened, the app remember your huge monitor size, and restore this huge size on your  laptop.

PRM did not check the current resolution when open a session, I will fix it latter.
