### ISSUE TITLE
The default port does not change when switching the connection type

### ISSUE THREAD

**Issue by cweijan** [VShawn/PRemoteM#167]
I want to add a VNC connection, but it shows the 3389 port, and the other type of connection is also the same.

我想添加一个VNC连接, 但他显示的还是3389端口, 换其他类型的连接也是一样.
![image](https://user-images.githubusercontent.com/27798227/144784869-057190a0-09d6-4bdb-a405-1e048d4c8fb6.png)
另外感谢一下你这个软件, 我在找一个能自动调整分辨率的开源RDP客户端, 你这个真不错.

**Comment by VShawn** [comment]
这个倒不是 BUG，而是...

```
1. 假设用户要添加一个 33 端口的 SSH
2. 他首先在 RDP 页面填好了 IP XXX.XXX.XXX 端口号 33
3 .然后发现选择错误了选项卡，这时切换到 SSH，此时端口号应该保持 33 不变
```

基于上述考虑，干脆就偷懒省事做成端口不变了。

This is not bug, but ...

`` `
1. Assume that the user wants to add a 33-port SSH
2. He first fills the IP xxx.xxx.xxx port number 33 on the RDP page.
3. Then I find the selected error tab, switch to SSH, at which time the port number should keep 33 unchanged
`` `

Based on the above considerations, it is simply lazy to make a port unchanged.

**Comment by cweijan** [comment]
这么说也有道理, 我是看你代码有个baseport=5900.

**Comment by VShawn** [comment]
> 这么说也有道理, 我是看你代码有个baseport=5900.

那个是早期设定，最终没用上 😂

**Comment by cweijan** [comment]
我安装了vs2022, .net4.8和win10 sdk, 但还是没办法编译成功, 你知道怎么解决吗
![image](https://user-images.githubusercontent.com/27798227/144819225-2d8b569a-8541-4055-970c-446aee305111.png)

![image](https://user-images.githubusercontent.com/27798227/144819478-3f020be9-bc0b-4a48-b206-803b64843324.png)

**Comment by VShawn** [comment]
你好，你还需要安装 Windows 10 SDK 10.0.17763.0

https://github.com/VShawn/PRemoteM/blob/dev/DEVELOP.md
