### ISSUE TITLE
希望能稍微调整一下连接面板

### ISSUE THREAD

**Issue by cweijan** [VShawn/PRemoteM#168]
一般情况下远程连接的连接信息是最主要的, 我刚安装的愣了一会才发现连接信息是在下方, 填写连接信息后又发现得填写连接名称才能完成连接, 如果把连接信息放在连接名称下面体验会好点.
![image](https://user-images.githubusercontent.com/27798227/144785111-822cd5fb-a761-44bd-aa1e-a90c813aeff4.png)

**Comment by VShawn** [comment]
告诉你为啥，因为上半部分是通用的，所以`连接`放在`常规`下方

![image](https://user-images.githubusercontent.com/10143738/144806352-4137b602-b9a8-4807-bffd-2407bbe0521f.png)

有些协议可能直接就不需要填IP地址，比如说：

![image](https://user-images.githubusercontent.com/10143738/144806719-317b336e-ed70-47e7-a6c0-1bc8bb6bcf41.png)

所以虽然不是不能把 address 放到前排，但现在这种显示方式也无伤大雅，再考虑到重构成本，修改以后需要更复杂的显示控制逻辑，修改后引入的新BUG，我觉得还是放一放。
