### ISSUE TITLE
Storing rdp-files does not work when username has blankspaces

### ISSUE THREAD

**Issue by enkelmedia** [VShawn/PRemoteM#17]
My username has a blank space and I get an error when trying to connect to a machine that i've created:

Invalid connection file (Johansson\AppData\Local\Temp\foo.rdp)

My username is Mark Johansson.

// m

**Comment by enkelmedia** [comment]
Found the issue
RemoteWindowPool.cs L124

Need to wrap the path with " " like this: 
```
p.StandardInput.WriteLine("mstsc -admin \"" + rdpFile + "\"");
```
After that change it works again

**Comment by VShawn** [comment]
thank you for report.:+1:
the bug has been fixed now
https://github.com/VShawn/PRemoteM/commit/0f4796f1498f97d668f7186d6a4843c88c3db034#diff-501fa1bd6fb1240581247547fb50e3d0R124

and here is the new release: https://github.com/VShawn/PRemoteM/releases/tag/0.4.8.2008150945
