### ISSUE TITLE
Parity of connection options between launcher and list

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#170]
**Is your enhancement related to a problem? Please describe.**

Launcher doesn't have same options as list of connections. Also, now right click button might be more problematic then before. as it can't show popup menu

**Describe the solution you'd like**

Not sure. Will think about it and edit later.

**Comment by VShawn** [comment]
I am sorry, i didn’t get you. 

And what do you mean `as it can't show popup menu`?

**Comment by VShawn** [comment]
ahhh I see, you mean here has no connection button.

![image](https://user-images.githubusercontent.com/10143738/145394826-2003b467-a348-4755-905b-cf38f4a9a0b0.png)



related issue:

there are 2 connection button in a same runner when you have no custom runner.

![image](https://user-images.githubusercontent.com/10143738/145394949-f96cb9ad-0e31-471b-b4ba-adbbe5777ec4.png)

**Comment by majkinetor** [comment]
Yeah, that. But only only that, whatever in future ends up on one place should be possible in other (currently copy XXX to clipboard is also missing) and there are some stuff missing on launcher (delete being one of them).

**Comment by VShawn** [comment]
> `some stuff missing on launcher`

it is been designed, I managed to separate launcher and list view:  the task of launcher is quick operation while the list view is for full functional management.

then I try to offer a non-management launcher to our user.  That's why launcher does not have a delete button and right click on list will go to edit page.

**Comment by majkinetor** [comment]
OK, so minimal stuff to do here is to modify hamburger menu of the current row to add additional options.
