### ISSUE TITLE
little inconvenience

### ISSUE THREAD

**Issue by PahaKush** [VShawn/PRemoteM#171]
In APP protocol connections Name of connection = Hostname (cant change separately).

**Comment by VShawn** [comment]
could u give a screenshot?

here I tested the name of APP protocol

![image](https://user-images.githubusercontent.com/10143738/145955924-49666974-aa22-4bcd-8c5d-2e269d3ee2bb.png)

**Comment by PahaKush** [comment]
![screen](https://user-images.githubusercontent.com/38435295/145958069-c6ec4cba-c15b-448a-a62e-0363af0eb519.png)
![screen2](https://user-images.githubusercontent.com/38435295/145958086-1e573b9e-88eb-427d-83ec-bb847a235ff5.png)
I meant it

**Comment by VShawn** [comment]
okeyyy, I see

it is good to show the `cmd parameter` here instead of the name.

**Comment by VShawn** [comment]
um...
too long to display

![image](https://user-images.githubusercontent.com/10143738/145974404-11cca369-62dc-48cb-a24a-d2e8bcda3f9f.png)
