### ISSUE TITLE
Custom RDP scale factor 

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#172]
One thing I've been trying to get is a RDP session
where the remote resolution is 1920x1080
and local resolution is 3840x2160
and the zoom is set to 200% so that it works full screen
(this is to avoid issues with other users connecting to the same box and scaling issues with icons)

So far I've only found the "Microsoft Remote Desktop App" on the windows store that does that
(both zooming and fullscreen at the same time), but the ui on that one is pretty awful compared to anything else

That would be a nice feature to have, but it sounds like you're limited by the ActiveX control

_Originally posted by @grbd in https://github.com/VShawn/PRemoteM/issues/26#issuecomment-992589805_

**Comment by VShawn** [comment]
@grbd

I downloaded the "Microsoft Remote Desktop App" and learn how it works with custom scale factor.

It is able to have in our PRemoteM, just nedd a little time to develop.

**Comment by grbd** [comment]
Thanks very much that would be very useful.
For the "Microsoft Remote Desktop App" I think what it's doing is not using the active-x version of full screen. But instead creating a resizable window or fixed resolution window that it then stretches out to full screen in it's own form. (which is sort of cheating but actually works fine.)

**Comment by VShawn** [comment]
@grbd hi new feature is available here: https://github.com/VShawn/PRemoteM/releases/download/0.6.0-beta/0.6.0-beta2.zip

**Comment by grbd** [comment]
Thanks I just tried it and it works really well

**Comment by majkinetor** [comment]
Not sure if its because of this update, but now I don't have my full screen connection resized:

<details><summary>details</summary> 

![image](https://user-images.githubusercontent.com/85767/146366230-ffe49309-fe48-4a2c-bfb6-e590413c5e22.png)


![prm2](https://user-images.githubusercontent.com/85767/146366073-7e3c4cd6-65cd-464e-821d-61983dc95182.gif)

</details>

I had this behavior before, but never with full screen option. It however does that on some other connections.

**Comment by VShawn** [comment]
definitely a bug, beta3 update needed. 😭

**Comment by grbd** [comment]
Yep just spotted it with the "Connect with full screen" ticked
if you come out of full screen then re-enter it then it works ok though

**Comment by majkinetor** [comment]
It solves on minimize/maximize combo. If you remember previously you worked on this (can't remember which ticket) when you did resize with some latency so it doesn't kick as soon as you connect. So this is basically the same problem...

**Comment by VShawn** [comment]
> It solves on minimize/maximize combo. If you remember previously you worked on this (can't remember which ticket) when you did resize with some latency so it doesn't kick as soon as you connect. So this is basically the same problem...


maybe I drunk or something, I just removed some key code stupidly.

this one ought to work


[0.6.0-beta2.zip](https://github.com/VShawn/PRemoteM/files/7727384/0.6.0-beta2.zip)

**Comment by majkinetor** [comment]
Works now. Awesome.
