### ISSUE TITLE
Multiple tag search

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#173]
**Is your feature request related to a problem? Please describe.**

Currently its not possible to show connections having multiple tags.

**Describe the solution you'd like**

Lets use `#xyz` phrase in search to create AND query. For example `#personal #server` would shows connections tagged both with personal AND server.  Negative tags should also be supported - `-#personal` for example to find connections NOT containing that tag.

**Describe alternatives you've considered**

There are no alternatives

**Additional context**
There could be sugar behavior later when this is implmented:

0. Click on tag replaces current search (we basically have this now)
1. CTRL click on tag adds it in search
2. (CTRL) right click on tag adds negative search (i.e. `#server -#personal` would show connections having `server` tag but not having `personal` tag)
3. Middle click on tag to show popup via which you can rename it or delete it (there could be more options, such as tag color and tag description but those are not that important).

With this there is only one IMO mandatory option that we need to have for efficient tag based workflow - adding or removing tags from group of connections (not just replacing all the tags as we have today).

**Comment by VShawn** [comment]
how this work in the launcher?

**Comment by majkinetor** [comment]
It could work exactly the same. Launcher search or list search, it shouldn't matter. 

So: 

1. `#database #project1` - find all connections containing both tags
2. `#database -#project1` - find all databases less those of project1
3. `#project1 foo` - find all connections containing project1 tag and among them, find those having `foo` somewhere (name, computer name, even tags with option to search within them enabled)

**Comment by majkinetor** [comment]
Awesome.

But, wait, why are you showing # in front of every tag on display? Its just marker for search type, it shouldn't propagate to tag name. It just adds noise IMO.

**Comment by VShawn** [comment]
in the launcher, PRM enter the TAG matching logic through the `#` prefix. In order to keep all TAG display formats, all the tags were added a `#` prefix.

**Comment by majkinetor** [comment]
Well ok, I think it just adds noise here since there are dedicated tag locations in PRM. When there is no dedicated location then it makes sense (e.g Twitter allows tags among narrative so it must have #).

**Comment by majkinetor** [comment]
We don't have multiple tag search in list view:

![image](https://user-images.githubusercontent.com/85767/151159379-76f5680a-0be4-40a0-ac07-57d0f65368d3.png)

![image](https://user-images.githubusercontent.com/85767/151159389-024bb4d0-d894-4c2d-bb1e-9f73a859b83a.png)

**Comment by majkinetor** [comment]
I will reopen this due to it not working in list view.

**Comment by majkinetor** [comment]
Great. I will start using it and report anything I find here.

**Comment by majkinetor** [comment]
FYI, existing database is deleted with this 0.6.2.beta2.zip
