### ISSUE TITLE
How to change SSH color schemes

### ISSUE THREAD

**Issue by moreant** [VShawn/PRemoteM#175]
Look like use KiTTY Session change  color schemes, But I’ve never used KiTTY , I don’t know how to set it up

**Comment by VShawn** [comment]
You can changed KiTTY theme here if you are using the 0.6.0 beta
( In 5.9 this opeion sitting in `Theme`  )

![image](https://user-images.githubusercontent.com/10143738/148191830-48d10712-7090-4047-983f-76cdf4a40dd1.png)

KiTTY theme custom is not supported now.

**Comment by moreant** [comment]
Thank you, I turned out to be using version 0.5.11
