### ISSUE TITLE
bring card view back

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#176]
Some told me he love card view much then the list view. I like card view too.  Just ... after I made a new configuration system in the 0.6.0, I found some strange UX bugs occur when I switch card view / list view, so I remove card view to reduce my workload.

since 0.6.0 become stable, it time to find card biew back.

**Comment by RajikDeymon** [comment]
Many many thanks!

**Comment by VShawn** [comment]
you are welcome : )
