### ISSUE TITLE
Microsoft Store Version is still 0.5.11.2

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#180]
**Describe the bug**
The Microsoft Store Version is still 0.5.11.2

**Expected behavior**
Please Update the Version to 0.6.0

**Screenshots**
![Screenshot 2022-01-10 123018](https://user-images.githubusercontent.com/73733823/148759178-15424886-a3d1-4eae-b6fb-71734e25ee13.png)
![Screenshot 2022-01-10 123057](https://user-images.githubusercontent.com/73733823/148759231-4ab6d986-13db-458b-a7a0-05e83ffec249.png)
**Desktop:**
 - OS: Windows 11 Pro

Thanks in advance.

Best regards. stetze

**Comment by VShawn** [comment]
Yes I know that, some issuses make me slow down the MS Store submit progress.  I decide upload to MS Store until 6.0.1 version is released (in a few days latter).

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/148878905-5afafc6d-d22d-46c1-8e8e-de5d34e44eca.png)

MS Store is on the way.

**Comment by stetze88** [comment]
Thank you very much. Something is wrong with my Installation...

<img width="316" alt="Screenshot 2022-01-12 102319" src="https://user-images.githubusercontent.com/73733823/149113710-5ecc94d4-61aa-4396-8db8-ba0b79365aee.png">

**Comment by VShawn** [comment]
emm...something goes wrong I have to disable prm form MS sotre and find out what‘s happened 😒

**Comment by stetze88** [comment]
I have a backup, not that bad. :-)

**Comment by majkinetor** [comment]
FFS just use chocolatey, its up there few hours after official release :)

**Comment by stetze88** [comment]
I will not use chocolatey. Maybe winget? :-) But Microsoft Store is very easy.

**Comment by majkinetor** [comment]
Winget sux at this point, maybe when it gests serious.

**Comment by VShawn** [comment]
> I will not use chocolatey. Maybe winget? :-) But Microsoft Store is very easy.

I will not use Microsoft Store. I choose the portable exe and don't care about the store version. Although I pay about $20 for the developer account LOL.

The most reason I can hardly download or update form the store. It always internet failure for Microsoft Store in my location. 

![image](https://user-images.githubusercontent.com/10143738/149278293-d1632fd2-1fa2-4573-b4d9-87f424802192.png)

**Comment by stetze88** [comment]
@VShawn 
That is sad. I think the store will become more and more popular. At the latest when the Android apps are available. Many popular small programs are now also represented in the store. Like Videolan, paint.net, WinSCP ... Maybe you could do it like WinSCP. The Microsoft Store Version is not free. He take the money for further development. And PRemoteM is a very good program, which must be further developed. :-) But your bug with the Microsoft Store is certainly very annoying.

**Comment by VShawn** [comment]
> But your bug with the Microsoft Store is certainly very annoying.

@stetze88  Maybe the [GFW](https://en.wikipedia.org/wiki/GFW) make this bug, I dont know. The fact is: my Microsoft Store  is available randomly. And my vpn gives no help for this. it's really annoying as you said.

**Comment by majkinetor** [comment]
On the other hand, I never had any problem with chocolatey. I hate automatic updates because they always fuck things up when you need it the most.   Store sux for other reasons too - you can't use it for related tools. Most great tools are NOT on the store too.

So in choco land, you

    cinst premtem winscp kitty nomachine whatever

then you `cup all` when you want to updated all packages at the same time. If you want it automatic, you schedule this.
