### ISSUE TITLE
Wrong program signature! The program is irremediably altered. Download a new version from official web site.

### ISSUE THREAD

**Issue by SofiaStar** [VShawn/PRemoteM#183]
![image](https://user-images.githubusercontent.com/52817349/150274258-cf6bb221-ed33-47fd-a77d-27a11c27f7bb.png)
![image](https://user-images.githubusercontent.com/52817349/150274291-483bc67e-7b28-4424-be69-3e0eec08889e.png)
![image](https://user-images.githubusercontent.com/52817349/150274525-916c7ea0-0598-403b-965c-ce1058090b7a.png)

**Comment by VShawn** [comment]
It appened again! #98 #117

KiTTY said it has "Wrong program signature!"

Since the  KiTTY is the offical version form http://www.9bis.net/,  I don't know the cause of the failure.

As a template solution, you can download the latest KiTTY from http://www.9bis.net/, and add it as the default ssh runner.

![image](https://user-images.githubusercontent.com/10143738/150284695-9ea557ac-2d61-4295-a375-928af08d57a1.png)

**Comment by VShawn** [comment]
您好，这个问题时有发送，我现在完全不能理解为何有这个提示。

https://github.com/VShawn/PRemoteM/issues/117

PRemoteM 的 ssh 是调用 KiTTY 实现的，而内置 KiTTY 又是 KiTTY
官方提供的（尽管已经不是最新版本了），实在没理由会提示签名错误，并且也不是每个用户都会收到这个提示。
我得去翻翻 KiTTY 的源码来检查一下到底发生了啥。

临时解决方案是你可以自己下载一个最新版本的 KiTTY ，然后把这个 KiTTY  设置为 SSH 的启动器。

[image: image.png]

**Comment by SofiaStar** [comment]
got it , thanks !

**Comment by VShawn** [comment]
@SofiaStar 对了，您可以协助测试一下，直接用软件自带的 KiTTY 连接SSH时，是否会弹出这个更新提示么？

软件自带 KiTTY 位于：
C:\Users\你的用户名\AppData\Roaming\PRemoteM\Kitty\kitty_portable_PRemoteM.exe

我刚才去搜索了 KiTTY 的源码，没找到 `Wrong program signature` 这句话。

**Comment by SofiaStar** [comment]
![image](https://user-images.githubusercontent.com/52817349/150288668-3527d9a9-f39c-4c33-891f-d117a36c4ae6.png)

测试了一下，依然是这个报错，不知道问题出在哪里，官网下载的kitty是OK的

**Comment by VShawn** [comment]
@SofiaStar 我的意思是，尝试直接进入目录 `C:\Users\你的用户名\AppData\Roaming\PRemoteM\Kitty\` 双击启动 Kitty，看还会不会有这个提示。

**Comment by VShawn** [comment]
I checked the MD5 of kitty_portable_PRemoteM.exe and [kitty_portable.exe v0.74.4.13](https://github.com/cyd01/KiTTY/releases/download/v0.74.4.13/kitty_portable.exe). 

got same value

![image](https://user-images.githubusercontent.com/10143738/150289557-0db3de19-998c-4874-8b2c-47ba69e8c340.png)

**Comment by SofiaStar** [comment]
我想我大概知道产生问题的原因了
![image](https://user-images.githubusercontent.com/52817349/150293614-d6c0817c-aad1-45a9-825f-413e21eb9e55.png)
是什么导致了这个情况，我没搞清楚，目前的现象来看，是相关资源并没有加载到实际的目录中去

**Comment by SofiaStar** [comment]
我想我大概找到本机的kitty不生效的原因了
![image](https://user-images.githubusercontent.com/52817349/150294151-057c40d4-a1c2-4e68-be0e-477b993ccca7.png)
kan看着像是某些资源在下载的时候没能进入实际的目录

**Comment by VShawn** [comment]
@SofiaStar 不对，explorer 内找不到 PRemoteM 的目录原因是 Microsoft Store 版本的软件会被系统在沙盒中运行，软件内访问到的目录是被映射出来的虚拟目录，并非是用户的真实文件目录。然而这些文件实际上是真实存在于某个沙盒中的，理论上不会导致`Wrong program signature! `这个故障。

我得找台完全没有开发环境的新电脑测试一下。

**Comment by stetze88** [comment]
![Screenshot 2022-01-20 112114](https://user-images.githubusercontent.com/73733823/150322562-dae2d1a1-271f-43a3-b5f0-fe151b9f6830.png)
![Screenshot 2022-01-20 113529](https://user-images.githubusercontent.com/73733823/150322569-0a005474-0183-43ff-9dd4-f3437470148e.png)

I have the same problem, how can i help?

**Comment by majkinetor** [comment]
I can't help while people speak here language I don't understand. I am not sure why you promote this @VShawn? Don't u have mirror on gettee?

**Comment by VShawn** [comment]
@majkinetor 
> I am not sure why you promote this.
I am not intend to impede people from using their native language here. If I dont understand I will try google translate or ask the guy  to describe it again in English. 

> Don't u have mirror on gettee?
I dont maintain the gitee mirror,  I never sign in gitee after I set it sync  from GitHub.

@stetze88 Thx, I have no idea to solve this problem at the moment, I will ask you for help if needed.

**Comment by stetze88** [comment]
![image](https://user-images.githubusercontent.com/73733823/150414468-6b952ae6-e76e-4652-8402-4659825cddbd.png)
I switched to the OpenSSH client from Windows. It works. :)

**Comment by VShawn** [comment]
Finally, I found why.


As a MS Store APP, if `C:\Users\Shawn\AppData\Roaming\PRemoteM`  was not existed before APP run. APP  will get a virtualization of this locations. And exe run from virtualization should be signed by my signature. 

> All newly created files and folders in the user's AppData folder (e.g., C:\Users\user_name\AppData) are written to a private per-user, per-app location but merged at runtime to appear in the real AppData location. This allows some degree of state separation for artifacts that are only used by the application itself, and this enables the system to clean up those files when the application is uninstalled. Modifications to existing files under the user's AppData folder is allowed to provide a higher degree of compatibility and interactivity between applications and the OS. This reduces filesystem “rot” because the OS is aware of every file or directory change made by an application. State separation also allows packaged desktop applications to pick up where a non-packaged version of the same application left off. Note that the OS does not support a virtual file system (VFS) folder for the user's AppData folder.


here is how to disable virtualization on Win10 21H1 and later,  https://docs.microsoft.com/en-us/windows/msix/desktop/flexible-virtualization

```
    <!-- If you don't want virtualization of file system writes to the user's AppData folder, then include the property, and set it to disabled. -->
    <desktop6:FileSystemWriteVirtualization>disabled</desktop6:FileSystemWriteVirtualization>
    
```

Maybe I should change a location to store Kitty

**Comment by majkinetor** [comment]
Great find. Amazing. 

Its probably good idea BTW to provide version without external tools included so we can use have those benefits:

1. independent update of tools
2. smaller download for users and upload for you
3. No more virus warnings because of external tools

In choco I can simply `cinst premotem kitty openssh whatever` to have them all up, running and interconnected (PRM could watch if there is kitty on PATH for example and use it if it finds it). 

Ofc, it can be done anytime.

**Comment by VShawn** [comment]
@majkinetor 
I considered two approaches: 1. Apply to disable the virtualization of AppData of MS Store; 2, no longer built-in Kitty. Currently in the assessment 1. If the it failed, I will turn to the 2.

**Comment by majkinetor** [comment]
The point is that you can have both, and it could just be a CI setting once there is some better CI :)

**Comment by VShawn** [comment]
> Apply to disable the virtualization of AppData of MS Store;

Passed, MS Store version has been upgraded.

![image](https://user-images.githubusercontent.com/10143738/151122015-a3d30227-21f4-430e-a1e4-3a99543e00d5.png)

> some better CI
