### ISSUE TITLE
Bulk removing common tags

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#184]
**Is your feature request related to a problem? Please describe.**

You can't easily tag list of connections. Currently we have bulk SET of tags, that means all existing tags will be replaced with new set. However, that is usually not what one wants in bulk tag edit - we want to add/remove specific tag(s) without affecting existing ones. 

For example:

1. C1 #db #web #linux
2. C2 #personal
3. C3 #foo #bar
4. C4 #web #db #linux

Now I say `-#linux` (#173) and get in results 2 & 3. Now I want to remember this result by adding new tag to it, lets say `#temp` so when I bulk ADD that tag I get:

1. C2 #personal #temp
2. C3 #foo #bar #temp

Now I can repeat this process and add `#temp` to results of other searches or by setting it on individual connections. 
End result is that I have `#temp` group of connections, I didn't kill any other groups (#personal #foo #bar) and can use this new tag to run bulk connection functionalities temporary (I can delete that tag later) or forever (leave it there) - for example bulk connect, export, username change etc.

**Describe the solution you'd like**

Add new bulk option in list view - Tags. It will open popup with fields such as those (screenshot from web service I make):

![image](https://user-images.githubusercontent.com/85767/150581039-c66e3319-5aa6-45c4-8338-19c25f4db4d0.png)

Set new tags here will replace all tags and we have that already but it could be useful to repeat it here.

**Describe alternatives you've considered**
You must go one by one on connections and add tags. This is not efficient with a lot of connections.

**Comment by VShawn** [comment]
> Currently we have bulk SET of tags, that means all existing tags will be replaced with new set.

No, add new tag won't replace the existing tags. And IMO your UI screenshot is too complicated

# 1

![image](https://user-images.githubusercontent.com/10143738/150738460-971831a8-2d09-4585-be91-a2cc1eca48f8.png)

# 2
![image](https://user-images.githubusercontent.com/10143738/150738687-31af41ec-a8bc-4a86-9fc6-26fef13a484a.png)

# 3
![image](https://user-images.githubusercontent.com/10143738/150739901-0062d24d-5c0a-4e59-ba59-7c548b59eb5e.png)

#4 
![image](https://user-images.githubusercontent.com/10143738/150739936-b39760df-5ab4-4922-81ad-a513637bfbf5.png)

**Comment by majkinetor** [comment]
Ah, it already works, how did I miss this.... 

Removing common tag isn't possible tho that easily but thats minor point.

**Comment by majkinetor** [comment]
Maybe you could update Tag diffing actually:

If I have 3 connections all having different tags, but all share few of them, then you could present it that way:

1. #1 #2 #3
2. #a #b #c #3 #1
3. #1 #3 #d #f

So when I bulk edit this I have `<different options>` while here it could be `<different options> #1 #3`. 

With this, you could remove #1 and #3 on all.

**Comment by VShawn** [comment]
ahh `So when I bulk edit this I have <different options> while here it could be <different options> #1 #3.`

I have already planned to do this, but I don't know why I missed it...

**Comment by majkinetor** [comment]
OK, I will reopen this then .

**Comment by VShawn** [comment]
this ticket has been done yesterday by https://github.com/VShawn/PRemoteM/commit/df4e637ee1325870cca64d791696e35df47eb12e

noticed CI is dead
