### ISSUE TITLE
SSH sessions not in Fullscreen on UHD Resolutions

### ISSUE THREAD

**Issue by FaySmash** [VShawn/PRemoteM#185]
**Describe the bug**
Since the Update to 0.6.1 SSH sessions don't use the Fullscreen anymore when running a UHD Display.

**To Reproduce**
1. Use UHD Display Resolution
2. Connect to a SSH session

**Expected behavior**
PremoteM should utilize the Fullscreen in SSH Connections.

**Screenshots**
Using RemoteM in FHD:
![FHD](https://user-images.githubusercontent.com/30392780/150584712-2f2ad4d4-4ead-4525-884d-99505e02b3c0.png)

Using RemoteM in UHD:
![UHD](https://user-images.githubusercontent.com/30392780/150584788-c9754bcc-1955-4180-81a4-cfa84d17f5db.png)

**Desktop (please complete the following information):**
 - OS: Win 11 Build 22000.434
 - PRemoteM Version 0.6.1

**Additional context**
Worked in previous Versions

**Comment by VShawn** [comment]
emm... I'm not sure why it does not work.

here test on my 4k 150% monitor with WSL Ubuntu20.04

![image](https://user-images.githubusercontent.com/10143738/150622276-526b0546-5088-4576-a229-a202d69c0423.png)

![image](https://user-images.githubusercontent.com/10143738/150622344-7aff6164-234a-448c-a907-fdabcbb3837d.png)

Tested on 0.6.1.1 with internal Kitty

![image](https://user-images.githubusercontent.com/10143738/150622370-fec2e1c3-5906-4696-b333-69d21d073794.png)

![image](https://user-images.githubusercontent.com/10143738/150622385-e3f182fc-477f-4201-adae-dcdcb5204f29.png)

**Comment by FaySmash** [comment]
That's what it looks like with 150% scaling:
<img width="1920" alt="UHD" src="https://user-images.githubusercontent.com/30392780/150654975-e7a130b8-5ff8-4830-8383-2aeca8fcd35f.png">

Same settings:
<img width="1176" alt="kitty" src="https://user-images.githubusercontent.com/30392780/150655005-efaccec4-f501-40fa-9b27-e0434761050a.png">

but I'm on 0.6.1 not 0.6.1.1

**Comment by VShawn** [comment]
fix it by restore the resize method to 0.5.11

**Comment by VShawn** [comment]
@FaySmash you can try it 
[PRemoteM-0.6.1.2-beta.zip](https://github.com/VShawn/PRemoteM/files/7919599/PRemoteM-0.6.1.2-beta.zip)

**Comment by FaySmash** [comment]
> @FaySmash you can try it [PRemoteM-0.6.1.2-beta.zip](https://github.com/VShawn/PRemoteM/files/7919599/PRemoteM-0.6.1.2-beta.zip)

that fixed it for me
