### ISSUE TITLE
Display option to maximize screen

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#187]
**Is your enhancement related to a problem? Please describe.**

We currently have 

![image](https://user-images.githubusercontent.com/85767/150639272-2cb67808-8f23-4b23-9b84-bf358c7c558c.png)

However, existing full screen options do not maximize locally screen, unless I am missing something.

**Describe the solution you'd like**

I would like to have an option to Maximize screen on starting up. It should work even with multiple tabs open, when some of the connections do not have this option - connection with this option will maximize its containing window.

**Describe alternatives you've considered**

The only other alternative is _Connect with full screen_ however that is not the same as I can't see any more my local taskbar.

**Comment by VShawn** [comment]
I dont understand how `Maximize screen on starting up` works?

do you means start a RDP with full screen size in a tab window like below gif?

![1](https://user-images.githubusercontent.com/10143738/150662584-3e260653-c086-4e18-9068-d7f87a65d59d.gif)


BTW, if `Connect with full screen` is disabled, PRM will remember the last state of your session. e.g. if you exit a rdp session with full-screen last time, then the next time you connect to the same server, PRM will start it with full-screen even the `Connect with full screen` is disabled.

Oh suddenly found, the current name of `Connect with full screen` should be `Connect with full screen if last time is full screen`

**Comment by majkinetor** [comment]
I mean local RDP/whatever window should be maximized always, just if I clicked on host maximize button (which I do constantly hence the request :) I rarely want to work in a window that is not maximized (we basically have RemoteApp for that case which fits that scenario much better).

> Connect with full screen if last time is full screen

This sounds awkward and longish :) How about _Keep last screen size_ and docs can explain further (and we will have more serious docs/site soon enough, I will do it if none else).

**Comment by majkinetor** [comment]
So, this _Resize_ option is just for the RDP "insides", right ? It doesn't influence whatsoever host window size. So the only option is _Connect full screen_ but as you said it should be named differently, which means that _Maximize window_ is reasonable non-existing option ?

**Comment by majkinetor** [comment]
Also _Resize_ option should IMO be renamed to _Fit content_  (Window desktop settings call this _Choose a fit_ and RDP _Display configuration_ which IMO doesn't convey the right meaning).

**Comment by VShawn** [comment]
>  So, this Resize option is just for the RDP "insides", right ? It doesn't influence whatsoever host window size.

Yes, I don't want the session to affect the size of its parent window. 

Assuming we have:
1. RDP1, it ask tab window to maximized size when connected.  
3. RDP2, it will auto adjust its resolution.

Now we have a tab window hosting a RDP2 session in 800X600 size, then we open the RDP1 and the the tab window control facing a conflict choice: 

1. keep it‘s size, then the RDP1 can not get the maximized  size
2. resize to maximized size, then the desk size of RDP2 will be changed out of my will.
3. what about open a new window? I don't like this approach, it make tab window control complex.

---

Oh BTW, if the lastset tab window you close is a maximized tab, the next session will be opened in  maximized tab.

> Also Resize option should IMO be renamed to Fit content

technical, I followed the mRemoteNG's approach: `auto resize`
![image](https://user-images.githubusercontent.com/10143738/150671485-ed5edf6f-dcc5-4069-b898-1a755f77cee6.png)

`Fit content` is good, but rename to `resolution` may be more clearly?

|  resolution   |  renamed options | old options |
|  ----  | ----  | ----  |
|    | Fit to window  | Auto adjust  |
|   | Custom resolution with stretch | Stretch  |
|   | Custom resolution without stretch |  Fixed  |
|   | Full-screen resolution with stretch | Stretch (full screen) |
|   | Full-screen resolution without stretch | Fixed (full screen) |

**Comment by majkinetor** [comment]
Regarding conflict:

1. One option is for last connection open to override whatever was previously open. Its expected, and you set it that way so if you don't want that, do not use Maximize.
2. Another option would be to resize windows on tab focus which is IMO annoying - clicking RDP1 tab again would maximize, then clicking RDP2 would restore to its w&h. This obviously sux due to the constant resizing that lasts few seconds.
3. Another option would be to open a new window and not add to existing tabs. We could have an option for this - _always open in separate window_.

All this sounds like overkill IMO, since its an option I wouldn't think too much about its cross-connection effects. I would personally set this to default for all connections and people that have a problem with cross-connection could either not use it, or use that _always open in separate window_ additional option.

**Comment by VShawn** [comment]
> All this sounds like overkill IMO 

I agree and IMO it's good to keep how it works of the tab window size.
