### ISSUE TITLE
Support remote copy/paste

### ISSUE THREAD

**Issue by stevelongRBC** [VShawn/PRemoteM#189]
I was considering switching from mRemoteNG to PRemoteM.  However, in my first session using RDP I found that I could not copy text from my local PC and paste it on the remote PC.

**Comment by VShawn** [comment]
Hi

Did your copy/paste works with MSTSC.exe? if MSTSC.exe works, then PRemoteM's copy/paste would works. (PRemoteM's  RDP calling the wrapper of mstsc.exe). As far as I know the copy/paste service of server side may die sometime(my Win2016), I have to reboot the server to bring it to life.

if MSTSC.exe works and PRemoteM not, you can contact me by Email for further diagnose.

**Comment by majkinetor** [comment]
Do you have this setting on: 

![image](https://user-images.githubusercontent.com/85767/150957712-7e60484f-1605-43cf-acad-aca950cc3b31.png)


If so, this happened to me on one server and restarting it (or remote desktop service) resolved it.

**Comment by stevelongRBC** [comment]
That was the issue.  I had imported my connection list from mRemoteNG csv and didn’t realize that there were separate settings for these features.  mRemoteNG has settings for the other resources, but I don’t see a setting for clipboard, so I guess that software enables clipboard by default maybe.  Anyway, once I checked the Clipboard box, it worked.  I will keep giving PRemoteM a try!

Thanks!

**Comment by majkinetor** [comment]
Note that you can select all connections, go to Edit and bulk set this option for all of them in case you have lots of them.

**Comment by VShawn** [comment]
Wait a minute, I remember that the import function should have the clipboard checked by default.

```
                            EnableClipboard = string.Equals(item.RedirectClipboard, "TRUE", StringComparison.CurrentCultureIgnoreCase),
```

EnableClipboard will be enabled if the field "RedirectClipboard" from mRemoteNG is TRUE.

https://github.com/VShawn/PRemoteM/blob/4c28cd0444b36707b92176ef4af31baf657ef64a/PRM.Core/Utils/mRemoteNG/mRemoteNGImporter.cs#L307-L309
