### ISSUE TITLE
Newly added tag can't be selected and it doesn't show among Tags

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#193]
**Describe the bug**

I add a new tag to single or bulk connections. After save, I see it among connection tags, but it can't be clicked, nor it shows among all tags.

After the PRM restart, it works normally.

**Comment by majkinetor** [comment]
It also doesn't show in tag autocomplete list

`test2` here is a new tag. `test` tag was shown here but is actually deleted:

![image](https://user-images.githubusercontent.com/85767/151058625-6bd0fcf1-e799-488f-a57a-3862dd7ff215.png)

**Comment by majkinetor** [comment]
New tag also doesn't show in autocomplete list (here `test2`)
 
![image](https://user-images.githubusercontent.com/85767/151059307-74bc70e6-a58d-4afa-9b9d-0959f7291c0c.png)

**Comment by VShawn** [comment]
I went out today with a mac book, and I will debug it tomorrow. : ）

**Comment by VShawn** [comment]
I can't reproduce this bug : (

**Comment by majkinetor** [comment]
It works in v 0.6.2-beta.

**Comment by VShawn** [comment]
![1](https://user-images.githubusercontent.com/10143738/155864354-3120b2f1-dbb6-4854-9b67-94ccf1fa21a3.gif)

**Comment by VShawn** [comment]
![1](https://user-images.githubusercontent.com/10143738/155919554-2bc8e69c-f89f-45c9-ab07-7e15b3558eaa.gif)

i dont know why it just works on me 😨

**Comment by majkinetor** [comment]
I tried on another machine, and the same behavior happens.

**Comment by VShawn** [comment]
please try this one, including all recently fix.

[0.6.2beta4.zip](https://github.com/VShawn/PRemoteM/files/8182853/0.6.2beta4.zip)

**Comment by majkinetor** [comment]
Works in beta4
