### ISSUE TITLE
Lost all Data / Config

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#195]
Today we Lost all our config / Data in premotem. In the ms Store an Update was availible, but the Version was still 0.6.1.1.

**Comment by VShawn** [comment]
the only change of this update is apply some permissions by statement below:
`
<desktop6:FileSystemWriteVirtualization>disabled</desktop6:FileSystemWriteVirtualization>
`

It fixed the bug that SSH could not be opened due to insufficient permissions of the store version. #183

I don't know this change will cause users to lose their data since it's not stated on the Microsoft's docs. And my data was stored in `D:/ ` not in the default path, so I didn't find this bug by my test.

Did you have any data backup? I can also submit an old version to you in the store through the test channel, and try to see if the old version can get the data back.

Anyway I'm so sorry.

**Comment by VShawn** [comment]
PRemoteM is unavailable to the Microsoft sotre now until I find how to fix this or simply add some caution for this update.

![image](https://user-images.githubusercontent.com/10143738/151279328-0d719461-fe76-493c-b66b-9dc28c950358.png)

**Comment by stetze88** [comment]
I checked the Old Pathes but the files are Lost. But it's Not so Bad. I have Only ~100 Servers and a few ssh connections. I will create them new and make than an Backup. :)

But for the other people who has not yet updated it will be good to know, that their need an backup of their config.

We use Windows 11 pro. Maybe this was an Problem?

**Comment by MoogierThanThou** [comment]
Happened also to me, using version 0.6.1.1 and installed from Store. I am also using Windows 11.
No big deal for me. Can be created again and good reminder for the backups. Thanks for doing this! :)

Other thing I've noticed in this version that reconnect doesn't work anymore (when using RDP and client gets locked).
Reconnect tries to log on again, but screen stays "black". I close the PremoteM and make connection again.

**Comment by VShawn** [comment]
@stetze88 @MoogierThanThou, no related to Win11. It happened when switching from virtualization to a real path, we will lost the data in virtualization path. But disabled the virtualization is the only way to solve the problem #183 of Microsoft Sotre verison. 

I have to decide whether to disable the virtualization or provide a version without KiTTY like majkinetor said:

> Its probably good idea BTW to provide version without external tools included so we can have those benefits:
> _Originally posted by @majkinetor in https://github.com/VShawn/PRemoteM/issues/183#issuecomment-1018776992

**Comment by majkinetor** [comment]
> I have to decide whether to disable the virtualization or provide a version without KiTTY like majkinetor said:

PRM is pre 1.0 software. This is expected. I wouldn't do anything. Bare bone PRM version without supportive tools can be done any time later and this shouldn't be main reason IMO but independent update, smaller binary, no AV problems.

**Comment by VShawn** [comment]
let's keep the virtualization disabled, I think it would be good for further development on store version. 
caution for database backup should be added.

**Comment by stetze88** [comment]
Maybe you Could add an export/ backup menu point(where you can Import the mremoteng file).

The "Migration" Point is Not easy to find. :-)

**Comment by majkinetor** [comment]
> Maybe you Could add an export/ backup menu point(where you can Import the mremoteng file).

I don't think this deserves development effort given you can just copy / paste this file anywhere or schedule that.

**Comment by VShawn** [comment]
> Maybe you Could add an export/ backup menu point(where you can Import the mremoteng file). 

We have export option when any data line was selected.
