### ISSUE TITLE
Add option to delete individual connections

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#198]
**Is your enhancement related to a problem? Please describe.**
Currently delete is only bulk option.

**Describe the solution you'd like**
Add delete option in menu. Confirmation too, maybe with option to skip it in advance ( [x] dont ask any more )

![image](https://user-images.githubusercontent.com/85767/153392156-e0027586-3fca-4e4e-812b-cbd13a00dbe4.png)

**Describe alternatives you've considered**
To use bulk, which is quite surprising.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/154475799-c381424f-7936-45ce-8fbc-1b17fa0b2b64.png)

delete button is available in the contex menu now.
