### ISSUE TITLE
在Windows11无法正常使用

### ISSUE THREAD

**Issue by cweijan** [VShawn/PRemoteM#202]
老哥你好, 在windows11连接远程时, 软件会卡死.
![image](https://user-images.githubusercontent.com/27798227/154189845-d6d7d5e6-8fc4-490d-8372-49c480c68f49.png)

**Comment by cweijan** [comment]
刚更新了一下windows11, 现在恢复正常了.

**Comment by VShawn** [comment]
> 刚更新了一下windows11, 现在恢复正常了.

┗|｀O′|┛ ~~，我已经从 win11 还原成 win10了。
