### ISSUE TITLE
软件优化建议

### ISSUE THREAD

**Issue by cweijan** [VShawn/PRemoteM#203]
我找了很多个软件, 能够对RDP自适应分辨率的软件只有你这个和Remotix(需付费), 你这个软件很牛逼, 但知道的人确很少, 我用了一段时间, 给几点建议:
1. 名字改名, 现在这个名字太离谱了
2. 简化连接步骤
3. 调整布局和颜色使其更加现代化

我不会写windows程序, 去年暴力魔改了一下, 你可以参考看看https://github.com/cweijan/PRemoteM
![image](https://user-images.githubusercontent.com/27798227/154205695-6a2496d0-8a94-401f-b1ec-a4ab77124982.png)

**Comment by VShawn** [comment]
非常感谢你的建议：

1. 我起名能力比较差，现在这个名称是从 mRemoteNG 上抄过来的，懒得换了，毕竟当初就是因为不满 mRemoteNG 的功能才另起炉灶的。知道的人少就少吧，用的人多了我也不一定维护的过来。而且我基本没进行过软件宣传，只在GitHub的issue里推荐了一下自己的软件，现在那么多人用已经出乎我的意料了（这得感谢某个德国人在他们论坛上给我写了篇推荐，以至于现在很多用户都是德国人:joy:）。
2. 确实不知道该怎么优化了，我觉得 alt + m 输几个关键词回车就能连接已经很方便了。
3. UI/UX 方面只能说见仁见智吧，我个人不喜欢你魔改后的效果图，太白了。但我也不是设计师，搞不清楚到底如何才算是“现代化”的UI/UX。另外就是 UI/UX 方面需要花费的精力实在是太多了，我级别上是从开发这个软件开始才深入接触带 UI 软件的开发的，桌面端软件又不像 vue 那样有大量的控件库脚手架，很多时候我心里想的效果我都完全无法自己实现出来。

---

目前我个人觉得这个软件已经进入一个稳定期了，现在的主要工作就是修修大家提的BUG。下一次大改动应该是会把程序用 .NET6 重构，到时候才会想对 UI 动手，如果有什么建议欢迎来提。

**Comment by VShawn** [comment]
再次感谢:kissing_heart:

**Comment by VShawn** [comment]
> 目前我个人觉得这个软件已经进入一个稳定期了，现在的主要工作就是修修大家提的 BUG。

打脸了，为了新增一个功能差不多重构了25%的代码。

**Comment by cweijan** [comment]
期待你的新版本, 另外问下这个有没有可能移植到electron, 用electron就比较容易做出漂亮的界面.
