### ISSUE TITLE
Connection color as window border

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#204]
![image](https://user-images.githubusercontent.com/10143738/154781363-8e40a042-4461-4c5d-adc1-b40c3576f388.png)

![image](https://user-images.githubusercontent.com/10143738/154781371-27f42bf6-da0f-4679-bb05-aab3d05aec2a.png)

It seems that the color does not make much benefits to our app. 

Is there any people use color as identification markers?  If not, I would suggest to remove color mark to get a thinner title bar.

like this

![image](https://user-images.githubusercontent.com/10143738/154781586-02717054-dd75-438b-acae-8ce06dc3c95f.png)

**Comment by majkinetor** [comment]
Yes, color in title bars should be removed as its not very identifiable. I didn't see it at all.

But IMO, we could keep color and perhaps find better way to show it, for example color items/rows in connection list and quick launcher, color blank RDP/whatever window during connection (now black) and/or add separate color column such as in this list:

![image](https://user-images.githubusercontent.com/85767/154813121-c654135d-a18f-436a-903d-8d134f129f6b.png)

Or use it as a window border

![image](https://user-images.githubusercontent.com/85767/154813337-d6c9c193-4b77-43d1-8111-35ea43fdda1b.png)

with options that can influence size and position such as  _border size: 2px_, _border corners: top_

**Comment by VShawn** [comment]
I‘ve tried the `Host window border` and found it disperse my attention a lot.

**Comment by majkinetor** [comment]
That the point if you want to be alerted you are on Production. This should be an option anyway, and probably off by default.

**Comment by majkinetor** [comment]
Check it out in dBeaver, also off by default:

<details><summary>details</summary> 

In the list

![image](https://user-images.githubusercontent.com/85767/155130633-2f7791f9-cb13-45c7-a701-f3e2116a431b.png)

GUI around the table and tab color:


![image](https://user-images.githubusercontent.com/85767/155130777-4cdcb33c-4f4c-422a-8a69-bdd9e0137760.png)
![image](https://user-images.githubusercontent.com/85767/155130935-2b4320b3-55ae-449b-b90b-81bbd214c027.png)

Its settable here and off by default:

![image](https://user-images.githubusercontent.com/85767/155130999-70db41d5-29b7-4c96-b698-a7371a3bebd6.png)

</details>

Its of tremendous help IMO. I am constantly alerted when on Production database and it screams all the time as it should.

**Comment by VShawn** [comment]
make something like:

# hidden by default

![image](https://user-images.githubusercontent.com/10143738/155317345-b9069607-a008-4b03-b9bf-cb775a1a8c65.png)

# once color is set
![image](https://user-images.githubusercontent.com/10143738/155317245-f5d8bc75-920e-4709-af66-a4424ab87ce3.png)

**Comment by VShawn** [comment]
close ticket now? 

![image](https://user-images.githubusercontent.com/10143738/155439069-1dbdccc4-14e3-4692-a5c1-6a3739a5696a.png)

this is not achieved yet.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/155516180-aa0a174d-dce7-4623-92cf-d1e25ec54030.png)

![image](https://user-images.githubusercontent.com/10143738/155516378-7125d4d3-89ec-4011-a1e3-ec50a42343c4.png)

![image](https://user-images.githubusercontent.com/10143738/155516283-cf1a88b1-1e42-438c-91e5-e1d94231c170.png)

**Comment by majkinetor** [comment]
This actually looks great :)
