### ISSUE TITLE
Can't run multiple instances under different users

### ISSUE THREAD

**Issue by alishchytovych** [VShawn/PRemoteM#206]
Hello,

I can't run the app under multiple users on the same server. Is it possible to make the check on the per user?

https://github.com/VShawn/PRemoteM/blob/c1be080afbe451c23b53a2d059be6cf79ea272e8/PRemoteM/App.xaml.cs#L215

**Comment by alishchytovych** [comment]
Maybe this approach works for you:
`
static class Program {
	public static Mutex Single;
	public static string AppId = "966b1f20-1a74-1234-af60-7072a1d55678";

	static void Main(string[] args) {
		if (Mutex.TryOpenExisting(Program.AppId, out Single))
			return;
		try {
			Single = new(false, Program.AppId);
			... run ...
		} finally {
			Single.Close();
		}
	}
}
`

**Comment by VShawn** [comment]
Ahhh. I didn't consider multi-user situation, you reminded me. 
I will find out how to make it work latter.

**Comment by VShawn** [comment]
There is a problem here. In portable app, If the two users edit data at the same time , the db of the APP may crash.

**Comment by majkinetor** [comment]
There could be a setting where to keep db - program dir or user dir. Even with portable app, this setting could by default target User directory. PRM could also accept db via cmd line while at it.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/155288222-162d2d29-204c-43e3-b6c5-e2256cb1fad7.png)

it works, I just leave that conflict risk alone : )z

**Comment by VShawn** [comment]
@alishchytovych you can try this beta version.
[0.6.2beta.zip](https://github.com/VShawn/PRemoteM/files/8123253/0.6.2beta.zip)
