### ISSUE TITLE
Protocol runner for WinScp is not ebedded

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#209]
**Describe the bug**

When I start WinSCP custom connection added as SFTP protocol runner, its shown in its own window.  This is not a big deal but it is inconsistent and some features do not apply like background color of the frame.

**Expected behavior**

To be shown among other connection tabs.

**Screenshot**
![image](https://user-images.githubusercontent.com/85767/155860214-1f39fb80-00ff-4fb4-a39e-5da907b04618.png)

**Comment by majkinetor** [comment]
This was disabled. When I enabled it, it was still outside but tab appeared. 

> sometime I just can not capture the handle of the external app window, and I can't move it into my tab window without that handle.

OK, when I find time I will inspect more about this...

**Comment by VShawn** [comment]
Yes sometimes it works, sometimes it fault when enabled `Hosting`.

Here is my two consecutive sessions:

![image](https://user-images.githubusercontent.com/10143738/156100336-708b37ac-35a8-4cce-ad41-147b865f6700.png)

**Comment by VShawn** [comment]
After some inspect.

In ticke #192, I remove the loop detect for the  external app's WindowHandle  to reduce cpu usage.
After this change, PRM can not get the real WindowHandle of WinSCP (because WindowHandle of WinSCP will change after it connected).
