### ISSUE TITLE
Launcher problems in v0.6.2-beta2

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#212]
There are number of problems with new launcher filtering in v.0.6.2-beta2:

1. Its glitchy when you type 
2. it has strange visual behavior (but I can live with it)
3. selection stays at previous position (should go back to first one after typing)
4. selected item no longer appears first in the list (high priority error, basically makes it next to unusable)

**Comment by VShawn** [comment]
I fix this in last commit yestday

[0.6.2.beta3.zip](https://github.com/VShawn/PRemoteM/files/8157834/0.6.2.beta3.zip)
