### ISSUE TITLE
Capture keyboard shortcuts by host

### ISSUE THREAD

**Issue by WeiMingLiu** [VShawn/PRemoteM#215]
**Is your feature request related to a problem? Please describe.**
In Remote Host ,how to type specify shortcuts captured by master to run some commands。Like Ctrl+Win+→to change master's virtual desktop, not remote host.
In mstsc，Use Ctrl +Alt+Home to jump focus out of remote host and then type shortcuts can be captured by master. it is a solution but not good enough,
PRemoteM can offer solutions to run shortcuts in remote host but captured by master?

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/156517847-b6398c77-d602-4e64-bc25-c248d50deeaf.png)

disabled the `key combinations` can help you.
