### ISSUE TITLE
RDP connection does not save different port

### ISSUE THREAD

**Issue by nikos1988** [VShawn/PRemoteM#217]
**Describe the bug**
RDP connection does not save different port

**To Reproduce**
1. Add RDP connection with non-default port, e.g. 8001
2. Save
3. Close PRemoteM completely
4. Start PRemoteM again
5. Saved RDP Connection suddenly has default port 3389 again

**Expected behavior**
Save RDP connection port correctly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 21H2 22000.556
 - PRemoteM Version 0.6.2 (Microsoft Store 1.0.39.0)

**Additional context**
Encrypted PRemoteM.db. Not sure if this has to do with the problem

**Comment by VShawn** [comment]
![1](https://user-images.githubusercontent.com/10143738/158126468-0a0db208-4eac-4dce-b3e0-560f6df34e65.gif)

Sorry, I can't reproduce it on Win10. 

IMO OS version would not bring this kind of bug.

**Comment by nikos1988** [comment]
Did you completely close PRemoteM and is your DB encrypted? I also checked the JsonConfigString with DBBrowser for SQLite and the port value does change. Maybe it does not load the port value correctly with encrypted DB?

**Comment by VShawn** [comment]
> Did you completely (via Trayicon) close PRemoteM

Yes

> is your DB encrypted?

No

I‘ll try again with encryption.

**Comment by VShawn** [comment]
oh yes you're right, it reproduce with encryption.
