### ISSUE TITLE
Centralize accounts in settings

### ISSUE THREAD

**Issue by coooly** [VShawn/PRemoteM#218]
Hello !
Could it be possible to centralize accounts in settings ?

Main value will be able to change an account password in one location instead of every connection using it.

Thank you

**Comment by majkinetor** [comment]
No, its not possible. 
There is easy alternative - you can bulk edit credential by selecting multiple connections. 

The only benefit of centralized editing is that you don't need to select connections which is really minor thing and you could tag  all those connections easily if you want later to be able to select this group with one click.

**Comment by majkinetor** [comment]
Duplicate: https://github.com/VShawn/PRemoteM/issues/89

**Comment by coooly** [comment]
Thank you. With a tag and bulk editing I can achieve easily what I was looking for. 😊
