### ISSUE TITLE
新增 Session 的快捷方式

### ISSUE THREAD

**Issue by Kerwin1202** [VShawn/PRemoteM#219]
> 目前有快捷键 ` Alt + M ` 拉起搜索的，但是有时候需要在远程的过程中新建 Session, 这时候只能 到托管图标双键打开才可以，能否新加快捷方式 或 在 `Alt + M` 搜索界面增加 `new` 之类的命名拉起新增

--
There are current shortcuts `Alt + M` pull up the search, but sometimes you need to create new session during the remote process, at this time you can only open the hosted icon dual key to open it, can you add a quick way or at `Alt + M` Search Interface Added a shortcut to add item.

**Comment by VShawn** [comment]
你好，我考虑了一下。
首先新增 Session 作为一个低频操作，我认为不应该添加到 launcher 里面。

其次，根据规划，未来的远程桌面tab窗口将留有一个页面显示现在的 Session 列表

像这样：

![image](https://user-images.githubusercontent.com/10143738/159100804-c7d39608-8c6c-41b2-bff5-fc7a81fa893e.png)

改进到这一版本后，就能轻易地在远程过程中新增 Session 了。
