### ISSUE TITLE
Multiple edit / default settings and empty user

### ISSUE THREAD

**Issue by ajtak-angelus** [VShawn/PRemoteM#22]
Hello,
it would be possible to multiple edit / default settings for RDP: Display / Advantage - Resources.
And then the option to have an empty field for user.

Thank you!

**Comment by VShawn** [comment]
thx for your advice.

1. is **multiple edit** means you can edit multiple protocol info in one time? i had been thinking about the *interactive mode* of it and got no idea, then i gave it up. 

2. **default setting** is useaful and will be available in the feature. But for now you can use **Duplicate** instead, the source protocol will be a template to add a new protocol info.

![Snipaste_2020-09-25_14-11-45](https://user-images.githubusercontent.com/10143738/94232698-278d1e80-ff39-11ea-82f5-1f6c2f7eb96c.jpg)

**Comment by majkinetor** [comment]
Also, why not right click on icon to go settings besides menu ? (its small, requires eye scan, mouse move, two clicks, all that vs right click on big box). 

Other two menu options are less important and probably used more rare.

**Comment by majkinetor** [comment]
Ticket #83 allows this among other things.
