### ISSUE TITLE
RemoteApp port issues

### ISSUE THREAD

**Issue by Kerwin1202** [VShawn/PRemoteM#220]
## 问题:
无法通过穿透使用 RemoteApp ，也想问问其他人有没有解决办法

## 起因:
RemoteApp 使用的是 3389 的 `UDP` 协议，直接服务器没问题。

但是我是异地两个内网想使用，所以用了 [FRP](https://github.com/fatedier/frp) 内网穿透。
修改了远程端口 `8991` 并且开启了 `tcp` `udp` `8991` 的端口转发，但是一直卡在这界面

mstsc 远程过程中，会显示质量良好已启用 `UDP`

![image](https://user-images.githubusercontent.com/16319833/158761351-ddbdac84-b994-4000-82ee-36bd462c10d6.png)

`NetLimiter` 监控是 `UDP` 走通的

![image](https://user-images.githubusercontent.com/16319833/158761662-cc6e7f3e-c533-470d-adc8-d50952dd28f3.png)

## 附上我的 `FRP` 配置

> frps server
```
[common]
bind_port = 7000
token = token
```

> 被控的 frpc
```
[common]
server_addr = myserver
server_port = 7000
token = token

[p2p_remote]
type = stcp
sk = 111111
local_ip = 127.0.0.1
local_port = 8991

[p2p_remote_udp]
type = sudp
sk = 111111
local_ip = 127.0.0.1
local_port = 8991

```

> 本地使用 frpc
```
[common]
server_addr = myserver
server_port = 7000

token = token

[p2p_remote_visitor]
type = stcp
role = visitor
server_name = p2p_remote
sk = 111111
bind_addr = 127.0.0.1
bind_port = 8991


[p2p_remote_udp_visitor]
type = sudp
role = visitor
server_name = p2p_remote_udp
sk = 111111
bind_addr = 127.0.0.1
bind_port = 8991
```

**Comment by VShawn** [comment]
这个可能需要你自己摸索了，我  RemoteAPP 用的比较少，更是完全没用过 FRP + RemoteAPP，无法提供有效的建议。
在之前看 RemoteAPP 的文档时也没有发现它会用 3389 以外的端口。

RemoteAPP 是完全基于系统自带的 mstsc.exe 启动的， 启动 RemoteAPP 时 PRemoteM 的操作是将RemoteAPP 的连接配置保存到一个临时的 .rdp 文件，然后通过命令行将这个临时 rdp 文件作为启动参数，启动 mstsc.exe，然后由 mstsc.exe 启动 RemoteAPP。
