### ISSUE TITLE
support ipv6

### ISSUE THREAD

**Issue by zhongshuiyuan** [VShawn/PRemoteM#225]
你好，不支持ipv6吗，当我服务器是ipv6时提示找不到注记。

使用私密连接时也是连接不上
![image](https://user-images.githubusercontent.com/8955999/161187623-6354ecbb-24e3-40bd-b108-8852d07326aa.png)

**Comment by VShawn** [comment]
不清楚能不能用ipv6耶，我没有ipv6的测试环境。看你的截图应该是 SSH 走 ip v6 对吧，ssh是基于 Kitty 的，可以参考这个：
https://github.com/cyd01/KiTTY/issues/43

I don't know if it can support ipv6. I don't have an ipv6 test environment.

**Comment by zhongshuiyuan** [comment]
ipv6加上[]就可以了，但另外一台oracle机子是ipv4，用私密，提示这个错误
![image](https://user-images.githubusercontent.com/8955999/161200296-c13bb4b6-88d4-40c6-93e2-0863b14be00e.png)

**Comment by zhongshuiyuan** [comment]
知道什么原因了，要用puttygen.exe进行私钥转换才行。
