### ISSUE TITLE
Sound can't be make to work with RemoteApp

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#226]
**Is your enhancement related to a problem? Please describe.**

I have foobar2k on my media center. I created RemoteApp and it works, but sound is not played on remote side. If I create the standard RDP connection and check sound option _Remote_, it works.

**Describe the solution you'd like**

Add Sound options just like with regular RD, and/or advanced mstsc settings and/or all RD options.

**Comment by majkinetor** [comment]
I managed to make it work by creating RDP file with _Remote App Tool_ then adding to it `audiomode:i:1`. This proves that setting works, it just need to be available within PRM.

**Comment by VShawn** [comment]
okey I‘ll check it latter

**Comment by VShawn** [comment]
https://github.com/VShawn/PRemoteM/blob/0.6.2_fix/PRM.Core/Protocol/RDP/ProtocolServerRemoteApp.cs#L67-L79

It's a bug that I set audiomode twice

**Comment by VShawn** [comment]
It's strange that according to the documentation

`audiomode:i:` option

- 0: Play sounds on the local computer (Play on this computer)
- 1: Play sounds on the remote computer (Play on remote computer)
- 2: Do not play sounds (Do not play)

`audiomode:i:1` means sounds will be play on the server, 

> I managed to make it work by creating RDP file with _Remote App Tool_ then adding to it `audiomode:i:1`. This proves that setting works, it just need to be available within PRM.

you sure it works?

**Comment by majkinetor** [comment]
Yeah, and that is how it should work based on documentation you provided - I wanted it to play on remote computer.

**Comment by VShawn** [comment]
Ahh... that's how you use the remote app.

I decided to add an option for remote app.

![image](https://user-images.githubusercontent.com/10143738/164421741-6faa1437-e098-4492-8efd-d380a23a7c46.png)

**Comment by majkinetor** [comment]
Nice. Thx

**Comment by majkinetor** [comment]
I can confirm that this works.
