### ISSUE TITLE
Resolution bug

### ISSUE THREAD

**Issue by zhj9709** [VShawn/PRemoteM#227]
**Describe the bug**

**To Reproduce**
1. 分辨率选择自适应
2. 最大化窗口，等待自适应分辨率
3. 最小化窗口
4. 又会出现自适应分辨率的过程，像是从全屏的分辨率变成自适应分辨率，可以看视频

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Win11 Pro Beta 22581.200]
 - PRemoteM Version [0.6.2.2]

**Additional context**

https://user-images.githubusercontent.com/13991774/161415996-2703d4b7-e2b1-494d-8a80-b83f9b1797a0.mp4

**Comment by zhj9709** [comment]
窗口不最大化好像没这个问题

**Comment by VShawn** [comment]
收到，感谢反馈。
我检查了代码，发现调整分辨率前会检查远程桌面窗口的尺寸是否变化，只有变化了才会继续执行调整分辨率的代码。所以按理说不应该出现你录屏的现象。并且这个现象在我本地 Win10 远程到 Win2016 或者 Win10 都无法复现。
所以我目前怀疑可能是和 Win11 有关，但我现在又没有 Win11 的机器来测试。

**Comment by zhj9709** [comment]
> 

我在Win10上也有这个情况，Win10 LTSC 1809。
但我有了新发现，直接使用软件上的最小化时，并不会调整分辨率。但如果我在通过点击任务栏上的图标最小化或是用Win+D回到桌面，再次打开就会重新调整分辨率。

**Comment by VShawn** [comment]
> 所以应该是windows对全屏的应用最小化时，重设了软件的大小

> 通过点击任务栏上的图标最小化或是用Win+D回到桌面，再次打开就会重新调整分辨率。

确实是这样，只有点击任务栏最小化时才会重新设置分辨率。两种最小化的表现不一致 Windows 或者 Winform 的锅。

**Comment by zhj9709** [comment]
@VShawn 当我使用PRemoteM时，最大化，没有全屏，电脑睡眠，远程连接的窗口没关，再唤醒，这时候PRmoteM应该会重新连接，远程连接的windows是锁屏状态，但输入密码进入桌面后，远程连接的画面好像变成了我本机的分辨率，并没有自适应最大化的分辨率。

**Comment by VShawn** [comment]
啊，这种情况确实没想到过。回头我测试一下。
