### ISSUE TITLE
VirusTotal Trojan.Malware.300983.susgen

### ISSUE THREAD

**Issue by stetze88** [VShawn/PRemoteM#228]
VirusTotal 1 security vendor and no sandboxes flagged this file as malicious.

Can you please check this?
I think it's false positive. But a green app is maybe better. :)
![Screenshot 2022-04-06 201311](https://user-images.githubusercontent.com/73733823/162041024-a5036e74-363f-4e84-a164-db71a0e8ea62.png)

**Comment by majkinetor** [comment]
You can ignore few positive results on Virus Total. For example, Chocolatey package repository ignores this:

https://community.chocolatey.org/packages/premotem#virus

![image](https://user-images.githubusercontent.com/85767/162047635-5ab251bb-d382-4596-a095-ba1feedf282c.png)

**Comment by VShawn** [comment]
Actually, I don't know how to avoid this. I know few about virus .

**Comment by majkinetor** [comment]
To avoid that one needs to provide info to that AV vendor on their specific page. I think that I personally wouldn't ever want to do that for the app I am making unless it was commercial.  

https://www.maxsecureantivirus.com/maxIS/submit_aFalse_Positive.htm

Just out of curiosity, I filled it in this time.
 
Also, anybody can comment on VirusTotal itself and mark finding as false.

**Comment by VShawn** [comment]
Any feeback from maxsecure?

**Comment by majkinetor** [comment]
Nah...

**Comment by VShawn** [comment]
Not surprisingly
