### ISSUE TITLE
en-us.json 404 Not Found

### ISSUE THREAD

**Issue by KernelGM** [VShawn/PRemoteM#229]
Erro when I try download: https://raw.githubusercontent.com/VShawn/PRemoteM/dev/PRM.Core/Languages/en-us.json
Say: 404 Not Found

**Comment by majkinetor** [comment]
Maybe you want this one?

https://github.com/VShawn/PRemoteM/blob/dev/PRemoteM/Resources/Languages/en-us.xaml
