### ISSUE TITLE
Please provide latest binary for download

### ISSUE THREAD

**Issue by BrommD** [VShawn/PRemoteM#23]
Hi,

the download link for latest release only provides the source code, but not a binary. Could you please check,

thank you

Best regards, Dejan

**Comment by VShawn** [comment]
Do you means 0.5.0.2010291925?
sorry but a serious bug was found on this version , so i delete its release.

Then the latest version update frequently these day to fix bug, and I will update release after a few days test. I will call you when next version was been released(tomorrow maybe).

let me know if you have any other ideas.

Have a good day, Shawn

**Comment by BrommD** [comment]
thx for letting me know!

**Comment by VShawn** [comment]
@BrommD the latest release you want is available here: https://github.com/VShawn/PRemoteM/releases/tag/0.5.1.2011110905
