### ISSUE TITLE
支持多开

### ISSUE THREAD

**Issue by Kerwin1202** [VShawn/PRemoteM#231]
希望支持多开，即用一个链接可以多个远程，目前发现有一个正在远程了，再点一次 没有新开而是跳转到原来的远程桌面（主要针对rdp，ssh 是支持的)

**Comment by VShawn** [comment]
RDP 本身就不支持多开啊，同一个服务器一个账号只能建立一个连接，想再开一个就必须新建一个账号。RDP 现在的表现是故意这样设计的。

**Comment by Kerwin1202** [comment]
默认是这样的，但是实际上是可以设置一个账号多开的

![image](https://user-images.githubusercontent.com/16319833/163901380-3fdefc14-2aa8-43ed-a593-d3e1b7aec233.png)

![image](https://user-images.githubusercontent.com/16319833/163901436-5c7cc696-51f3-4974-977a-d94c68ceb6cf.png)

**Comment by VShawn** [comment]
> 默认是这样的，但是实际上是可以设置一个账号多开的
> 
> ![image](https://user-images.githubusercontent.com/16319833/163901380-3fdefc14-2aa8-43ed-a593-d3e1b7aec233.png)
> 
> ![image](https://user-images.githubusercontent.com/16319833/163901436-5c7cc696-51f3-4974-977a-d94c68ceb6cf.png)

抱歉我说错了，我这里的RDP全都指的个人版PC，就是WIN10、WIN11这种，同一个账号重复会把上一个踢下线，所以我设置了RDP只能单开。我自己平时都不用server系统，所以没想起来你可能是用的服务器版Windows，惯性思维了抱歉抱歉。


不过你这样同一个账号开多个远程桌面有什么实际作用么？如果允许RDP多开，那么就会产生个人版系统多开时踢下线的问题了。

**Comment by Kerwin1202** [comment]
作用到是少数，比如需要复制文件到服务器的时候，通常复制过程不能使用，一用就复制断开，当然也可以由 ftp 等方式复制，所以有时候会新开一个使用。

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/163906288-cc70cd50-3156-4c1f-b725-bd38a55866e8.png)

我测试了一下，我的华为云服务器默认情况下也没法支持同一个账号多开连接，你是不是设置了什么才能这样用的？

这个多开支持起来要改动几个模块的逻辑，大概涉及几百行代码吧。
而且这个需求可能会降低大部分用户的体验....考虑还是不改了

**Comment by Kerwin1202** [comment]
所以说默认情况下是不支持的，包括服务器
