### ISSUE TITLE
Launcher cannot be opened again after being closed by Alt + F4

### ISSUE THREAD

**Issue by ckisaboy** [VShawn/PRemoteM#232]
windows 环境下
当我打开一个SSH连接窗口后以'Alt + F4' 的方式关闭窗口后, 无法再以'Alt + M' 的方式呼出快捷窗口

**Comment by VShawn** [comment]
感谢反馈，bug 确认存在，不过我遇到的是 ALT + F4 关闭窗口后，Alt+M可以打开启动器，但无法再次启动 SSH
