### ISSUE TITLE
Wrong item is being edited 

### ISSUE THREAD

**Issue by Kerwin1202** [VShawn/PRemoteM#233]
当我去编辑的时候，始终跳到第一个，如图，点击非第一个右键->编辑-> 预期是编辑我选择的这个, 但是实际上编辑的是第一个

![image](https://user-images.githubusercontent.com/16319833/165240439-367a1a3e-978a-4e14-93e7-dea52fea47db.png)

**Comment by VShawn** [comment]
Yes, confirm the bug, thanks for your report : )

![1](https://user-images.githubusercontent.com/10143738/165270768-74159500-5d7f-4dec-bd18-0f3b26f2b4c6.gif)
