### ISSUE TITLE
任务栏关闭窗口会把进程关闭

### ISSUE THREAD

**Issue by Kerwin1202** [VShawn/PRemoteM#234]
如果有主窗口打开的时候，这个操作会关闭进程
![image](https://user-images.githubusercontent.com/16319833/168093300-ed136cc5-a9bd-4c69-9817-0ce0ee6d4904.png)

这个关闭就不会
![image](https://user-images.githubusercontent.com/16319833/168093438-c5f83b46-9bd1-40e6-9dcb-99ed58589300.png)

**Comment by VShawn** [comment]
感谢反馈 bug，这个问题我已经在 dev 分支中修复过了，暂时还没发布稳定版本出来。

**Comment by Kerwin1202** [comment]
0.7 那个分支没有包含进去么，因为我是自己编译的这个分支最新的

**Comment by VShawn** [comment]
0.7 分支是完全重构的分支，可能这部分代码还没加进去，你稍微等待，最迟明天我加上并推上去。

0.6.1 以上的 release 版本都修了这个问题了。
