### ISSUE TITLE
Button or shortcut for reconnect session

### ISSUE THREAD

**Issue by dumy** [VShawn/PRemoteM#24]
If possible, reconnect to the session, because now I have to close it and then reopen the session. If possible, a shortcut would be welcome. Thank you very much for the application is very good.

![image](https://user-images.githubusercontent.com/8275027/99403919-aed09000-28f3-11eb-89a1-0740ab0c4391.png)

**Comment by VShawn** [comment]
got it, you will see the button on next release.

**Comment by dumy** [comment]
> got it, you will see the button on next release.

thank you very much, it's great project

**Comment by VShawn** [comment]
@dumy reconnect button is now available: https://github.com/VShawn/PRemoteM/releases/tag/0.5.1.2011192133

**Comment by dumy** [comment]
@VShawn  Thx very much, it's so easy utility
