### ISSUE TITLE
Add button on tab

### ISSUE THREAD

**Issue by dumy** [VShawn/PRemoteM#25]
I suggest you add button on tab. This button launch list servers like when execute ctrl + m. It's another idea, for you. 
![image](https://user-images.githubusercontent.com/8275027/100233408-6556f500-2f32-11eb-9893-146453dccd67.png)

**Comment by VShawn** [comment]
thx for your nice idea, here is the improve version:
https://github.com/VShawn/PRemoteM/releases/tag/0.5.2.2011271900
