### ISSUE TITLE
Export/Import

### ISSUE THREAD

**Issue by profbaco** [VShawn/PRemoteM#27]
Is there an option to export/import all my connections at once?
=============
Existe a opção de exportar/importar todas as minhas conexões, de uma única vez?

**Comment by VShawn** [comment]
of coz, hers is the export/import opetion


> de coz, dela é a opção de exportação / importação




![Snipaste_2020-12-05_10-10-08](https://user-images.githubusercontent.com/10143738/101230766-32ef8980-36e2-11eb-9b5f-ea9eda9c5df8.jpg)
