### ISSUE TITLE
Translation to PT-BR

### ISSUE THREAD

**Issue by profbaco** [VShawn/PRemoteM#29]
I translated the system into Brazilian Portuguese (PT-BR) and I will send you the file by e-mail. Do I send here too?

======================
Eu fiz a tradução do sistema para o idioma Português do Brasil (PT-BR) e vou te mandar o arquivo no e-mail. Mando por aqui também?

**Comment by VShawn** [comment]
hi thank you for your translation, you can send by email or upload here, it's on your choose, both are fine with me.

but it‘s best for you to fork and commit a pull request so that your name can be shown as a contributor of this repository  by GitHub.

Contributor will be shown on home page and here : https://github.com/VShawn/PRemoteM/graphs/contributors

---

Thank again for your contribution.

**Comment by profbaco** [comment]
That’s it, we’re here to improve the tool. I forked it, but I don't program with C #, only in PHP. Do I create the manual translation folder?
=========================
Que isso, estamos aqui para melhorar a ferramenta. Eu fiz o fork dele, mas eu não programo com C#, somente em PHP. Crio a pasta manual de tradução?

**Comment by VShawn** [comment]
don't worry 👍 , just fork it and place your  pt-br.js (named in lower case is better) into  directory PRM.Core\Languages. 
then commit and pull merge request. I will finish remaining work. 

![image](https://user-images.githubusercontent.com/10143738/101477047-9ea75000-3989-11eb-84cd-2a691c7c5fab.png)

**Comment by profbaco** [comment]
Ok, file uploaded (Ok, arquivo enviado)

**Comment by VShawn** [comment]
sorry? but i not receive any pull request.

![image](https://user-images.githubusercontent.com/10143738/101559732-b10ea180-39fc-11eb-9cfc-c8d24ce5f713.png)

---
## BTW

if you are using Win32 version PRemoteM, copy your json file into

> C:\Users\{YourName}\AppData\Roaming\PRemoteM\Languages

restart PRemoteM, then your new language will be shown in language selections. 

this little trick just for test.

**Comment by profbaco** [comment]
How strange. I will make a clone of the project as a whole then, and I will update it.
I did as you asked: I saved the file in the folder, stopped the program and restarted it, and it didn't load the language.
===========================
Mas que estranho. Vou fazer um clone do projeto como um todo então, e vou atualizar ele. 
Fiz como vc pediu: Salvei o arquivo na pasta, parei o programa e reiniciei ele, e ele não carregou o idioma.

![image](https://user-images.githubusercontent.com/5287317/101564884-b9d68780-39aa-11eb-9219-2062bcd093de.png)

**Comment by VShawn** [comment]
ahhhh I knew what happened : I closed the compile option of auto loading external json for public release , so it only works on my computer 😫. sorry for the wrong tip ,and I will make a debug version for you latter .

**Comment by VShawn** [comment]
colse by absent for long.
