### ISSUE TITLE
Import from CSV from mRemoteNG doesn't work

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#30]
**Describe the bug**

mRemoteNG v1.77.1.27713 (installed from Choclatey: `cinst mremoteng`)

**To Reproduce**

Not sure. Here is 1 CSV line with header and password set to ****:

```
Name;Id;Parent;NodeType;Description;Icon;Panel;Username;Password;Domain;Hostname;VmId;Protocol;PuttySession;Port;ConnectToConsole;UseCredSsp;UseVmId;RenderingEngine;ICAEncryptionStrength;RDPAuthenticationLevel;LoadBalanceInfo;Colors;Resolution;AutomaticResize;DisplayWallpaper;DisplayThemes;EnableFontSmoothing;EnableDesktopComposition;CacheBitmaps;RedirectDiskDrives;RedirectPorts;RedirectPrinters;RedirectClipboard;RedirectSmartCards;RedirectSound;RedirectKeys;PreExtApp;PostExtApp;MacAddress;UserField;ExtApp;Favorite;VNCCompression;VNCEncoding;VNCAuthMode;VNCProxyType;VNCProxyIP;VNCProxyPort;VNCProxyUsername;VNCProxyPassword;VNCColors;VNCSmartSizeMode;VNCViewOnly;RDGatewayUsageMethod;RDGatewayHostname;RDGatewayUseConnectionCredentials;RDGatewayUsername;RDGatewayPassword;RDGatewayDomain;RedirectAudioCapture;RdpVersion;InheritCacheBitmaps;InheritColors;InheritDescription;InheritDisplayThemes;InheritDisplayWallpaper;InheritEnableFontSmoothing;InheritEnableDesktopComposition;InheritDomain;InheritIcon;InheritPanel;InheritPassword;InheritPort;InheritProtocol;InheritPuttySession;InheritRedirectDiskDrives;InheritRedirectKeys;InheritRedirectPorts;InheritRedirectPrinters;InheritRedirectClipboard;InheritRedirectSmartCards;InheritRedirectSound;InheritResolution;InheritAutomaticResize;InheritUseConsoleSession;InheritUseCredSsp;InheritUseVmId;InheritVmId;InheritRenderingEngine;InheritUsername;InheritICAEncryptionStrength;InheritRDPAuthenticationLevel;InheritLoadBalanceInfo;InheritPreExtApp;InheritPostExtApp;InheritMacAddress;InheritUserField;InheritFavorite;InheritExtApp;InheritVNCCompression;InheritVNCEncoding;InheritVNCAuthMode;InheritVNCProxyType;InheritVNCProxyIP;InheritVNCProxyPort;InheritVNCProxyUsername;InheritVNCProxyPassword;InheritVNCColors;InheritVNCSmartSizeMode;InheritVNCViewOnly;InheritRDGatewayUsageMethod;InheritRDGatewayHostname;InheritRDGatewayUseConnectionCredentials;InheritRDGatewayUsername;InheritRDGatewayPassword;InheritRDGatewayDomain;InheritRDPAlertIdleTimeout;InheritRDPMinutesToIdleTimeout;InheritSoundQuality;InheritRedirectAudioCapture;InheritRdpVersion
vm-mmilic [nil];dc6cb033-b673-4aaf-b4d4-b4c05a06fddb;1364dba9-2097-4fb4-b8f2-ab9232618777;Connection;vm-1-dev-mmilic;mRemoteNG;General;nil.com\mmilic;*********;nil.com;vm-mmilic;;RDP;Default Settings;3389;False;True;False;IE;EncrBasic;NoAuth;;Colors16Bit;FitToWindow;True;True;True;True;True;True;True;False;False;True;False;DoNotPlay;True;;;;;;True;CompNone;EncHextile;AuthVNC;ProxyNone;;0;;;ColNormal;SmartSAspect;False;Never;;Yes;;;;False;Highest;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;False;
```

**Expected behavior**

It shows success. Nothing else. No number of items, imported items, errors and so on...

**Desktop (please complete the following information):**
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19042 N/A Build 19042
 - PRemoteM Version: 0.5.5.2012072119 (please make it copy/pastable in about box)

**Additional context**
Nothing, just wanted to try alternative to mRemoteNg. It looks like WIP but I totally like it so far, its way faster to resize and has saner config.

Also, as related now, UI buttons text are cut:

![image](https://user-images.githubusercontent.com/85767/101524229-f5148e80-3989-11eb-803c-61eac644695c.png)

**Comment by VShawn** [comment]
## bug fixed.
![image](https://user-images.githubusercontent.com/10143738/101563274-ee2a6200-3a03-11eb-837a-0f097f6025d0.png)

https://github.com/VShawn/PRemoteM/commit/64702148388a86e130b2bc69d08a55aac6c9a9ee bring in this bug by error logic

## UI buttons text are cut
no idea, UI works good for me 😕 

![image](https://user-images.githubusercontent.com/10143738/101564656-7f023d00-3a06-11eb-84a3-8da4e2207658.png)

**Comment by majkinetor** [comment]
Thanks, I'll just close this then.

**Comment by majkinetor** [comment]
Regarding cut, my Windows is set to 125% which is probably the reason why:

![image](https://user-images.githubusercontent.com/85767/101604287-faf98680-3a00-11eb-8892-de723e4ea50e.png)

**Comment by majkinetor** [comment]
Its still a bug with 125%, you should take that into account when refactoring UI, otherwise, you can call it pedantic.

**Comment by VShawn** [comment]
> Its still a bug with 125%, you should take that into account when refactoring UI, otherwise, you can call it pedantic.

that's it, it is the reason of cut off, no idea how to fix it now. Google for solution latter when i back home : )

---

BTW, new version to fix bugs has been released https://github.com/VShawn/PRemoteM/releases/tag/0.5.5.2012072119

**Comment by majkinetor** [comment]
It works now, it imported all my mRemoteNg stuff.

However, it import containers as items, not groups. mREmoteNG has nodeType Container which is similar to your groups (albeit better since you can't have groups within groups).  It would be nice to import at least 1 level containers or make it equivalent  in features as mRemoteNg.

Also, in mRemoteNG containers provide common parameters via inheritance, but that is some other topic.

![image](https://user-images.githubusercontent.com/85767/101631140-2e014180-3a24-11eb-8cbc-93c4f53f7054.png)

vs

![image](https://user-images.githubusercontent.com/85767/101631462-a5cf6c00-3a24-11eb-80fc-4b201147c451.png)

**Comment by VShawn** [comment]
> However, it imports containers as items, not groups. mREmoteNG has nodeType Container which is similar to your groups (albeit better since you can't have groups within groups). It would be nice to import at least 1 level containers or make it equivalent in features as mRemoteNg.


https://github.com/VShawn/PRemoteM/blob/dev/PRM.Core/Model/SystemConfig.DataSecurity.cs#L731-L770

i pull a new release to fix this.
