### ISSUE TITLE
If autostart option is selected, UAC prompt is shown even if you just exit the options

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#31]
**Describe the bug**

Enable autostart in options, say yes in UAC, go Back, say YES again?

Now just enter options and exit, UAC will prompt

**Expected behavior**

Do not show UAC prompt when there is no admin changes.

**Comment by VShawn** [comment]
the fact is in win32 version, i create/delete shutcut in 

> C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp

it needs admin authorization, so UAC show up.

But it is weird that UAC prompt twice, I will go for a check, it only prompt onece in previous version.


---

BTW, if you are using Stroe version, there should be on UAC prompt.

**Comment by majkinetor** [comment]
I confirm this works
