### ISSUE TITLE
Ability to use /admin in RDP-sessions

### ISSUE THREAD

**Issue by Shooshka** [VShawn/PRemoteM#32]
Please add ability/checkbox to use /admin key in RDP-sessions.

**Comment by VShawn** [comment]
Hi!
I did add a property(invisible for release version)

https://github.com/VShawn/PRemoteM/blob/4e6ab0847103fecff0a3a093bc13650fb56abe7f/PRM.Core/Protocol/RDP/Host/AxMsRdpClient09Host.xaml.cs#L259

just  not sure if  <kbd>ConnectToAdministerServer  = true</kbd>  ==   <kbd>/admin</kbd>

https://docs.microsoft.com/en-us/windows/win32/termserv/imsrdpclientadvancedsettings6-connecttoadministerserver

**Comment by VShawn** [comment]
the option is shown on the latest release, you can give a try
https://github.com/VShawn/PRemoteM/releases/tag/0.5.4.2012091641

![image](https://user-images.githubusercontent.com/10143738/101614041-69f9ce00-3a47-11eb-8839-6fdc652ab75a.png)

**Comment by Shooshka** [comment]
Don't see any .exe in releases, only source code..

**Comment by VShawn** [comment]
well i updated it 15min ago. Or maybe I uploaded a wrong package

**Comment by VShawn** [comment]
i upload again， please check again

**Comment by Shooshka** [comment]
Got it. Checkbox works as it should, ty!
