### ISSUE TITLE
Unclickable menu

### ISSUE THREAD

**Issue by Shooshka** [VShawn/PRemoteM#33]
Click on "+" or use Alt+M --> RMB click on any of connections --> Cannot edit/duplicate/etc, any option unclickable in this menu.

**Comment by VShawn** [comment]
sorry I don't get how to reproduce the bug？

I tried RMB click server card and it did goes into edit page and can edit options of it

**Comment by VShawn** [comment]
did you mean RMB click launcher list item? It's not design for click，after alt+M try press keyboard right key😀

**Comment by Shooshka** [comment]
> did you mean RMB click launcher list item?

Yep,

> It's not design for click

But if I can... I can! ;)

To be clear, I'm about this:

![2020-12-09_14-34-31](https://user-images.githubusercontent.com/1889052/101624917-bdf6b980-3a2b-11eb-88f1-3a8e87daa8f3.png)

**Comment by VShawn** [comment]
In fact in theverybeginning, i design luancher all actions called only by keyboard.

But it's ok to add some mouse event🤔, i will inform you when i upgrade this


anyway i will add more information in guidance

**Comment by VShawn** [comment]
new release package fix this issue.
