### ISSUE TITLE
Right click in launcher shows menu which doesn't work

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#35]
**Describe the bug**

Left clicking on any item does nothing.

![image](https://user-images.githubusercontent.com/85767/101633252-4a52ad80-3a27-11eb-8550-2dc631e9f5e2.png)

**Comment by VShawn** [comment]
as https://github.com/VShawn/PRemoteM/issues/33#issuecomment-741723352 said,  i not implement the click callback function here, i will add it next time.

**Comment by majkinetor** [comment]
Sorry, didn't know about it, closing as duplicate.

**Comment by VShawn** [comment]
> Sorry, didn't know about it, closing as duplicate.
 It dosen‘t matter, thanks anyway.

new release package fix this issue.
