### ISSUE TITLE
Huge memory leaks

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#37]
**Describe the bug**

The application is leaking huge amounts of memory. While it is pretty snappy and fast during work, it slowly hogs the system down. Each time you start RDP session, it goes up. When nothing works (no session is active and PRM is in tray) it keeps all that memory.

The image bellow is after starting and closing 3 RDP connections total 15 times (which I do in my usual work in few hours) and letting it stay for the night (to see if the GC will kick in but it didn't). You can see it eats 2+ GB memory which is double the next most hungry app - Chrome browser.

![image](https://user-images.githubusercontent.com/85767/101979452-82dbcc80-3c5d-11eb-9fc8-00924c495571.png)

**Expected behavior**

At least when no session is running and PRM is in tray, it should go next to the zero.  This kind of tools should never use more then few hundred MBs.

**Comment by VShawn** [comment]
bug confirm.
It seems like unrelease of AxMSTSCLib, but I tried *Dispose()* which gives no help at all. 
More document about how the exit AxMSTSCLib correctly is needed.

![image](https://user-images.githubusercontent.com/10143738/102000669-c3524d80-3d24-11eb-8fe2-df5145e51241.png)
![image](https://user-images.githubusercontent.com/10143738/102000688-00b6db00-3d25-11eb-9a28-11078d38d706.png)

**Comment by VShawn** [comment]
looks like works

![image](https://user-images.githubusercontent.com/10143738/102008251-3631e780-3d6a-11eb-90ba-b5b47ea4d891.png)

**Comment by majkinetor** [comment]
Gr8. I'll test it again when you release this.

**Comment by VShawn** [comment]
i found the huge memory leaks are fixed, still some little memory growth, I ignored them this time.

**Comment by majkinetor** [comment]
I confirm this. It still eats memory quite a bit, without any connection just by bringing launcher it takes 150MB while it should probably take ~10... but that is all tolerable in current paradigm where electron apps can take much more doing no more then todo management.
