### ISSUE TITLE
Possibility to have host only hotkeys

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#40]
**Is your feature request related to a problem? Please describe.**

It would be awesome to have hotkeys that influence host of the remote sessions even when you are working on remote side. 

Typical case is ALT TAB which you would like to execute on host rather then on the remote, for instance, to go to next machine. This today requires multiple hotkey and/or mouse clicks.

**Describe the solution you'd like**

I don't know if that is possible, judging from the CTRL + ALT + HOME which brings connection bar in full screen it is possible.

So this would be some a) definable hotkeys, or b) single key that when pressed redirects other keys to the host.

a) I define for example SHIFT + ALT + TAB to be ALT + TAB on host or SHIFT + CTRL + TAB to go to next tab on host
b) I define SHIFT to be a prefix, and I get above mentioned hotkeys immediately. Less flexible but good enough for most cases and easier to implement.

**Describe alternatives you've considered**
Didn't really research this more...

**Comment by VShawn** [comment]
## Unfortunately 
I found it impossible for local machine to capture hot key directly when you are in a RDP session or embed app like SSH via KiTTY.

but if you are in SFTP\FTP session, you can through by Ctrl + 1、Ctrl + 2, I add them before I found no way to capture hotkey in RDP session.

---
🤔  not sure if windows global hooks can work in these case. no test.

discussion may help:

https://superuser.com/questions/296633/windows-remote-desktop-how-to-untrap-keyboard
https://superuser.com/questions/207534/keyboard-shortcut-to-minimize-remote-desktop
https://forum.devolutions.net/topics/2788/toggle-keyboard-capture-for-windows-key-alttab
