### ISSUE TITLE
Minimize/restore flicker on maximized windows

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#41]
**Describe the bug**

There is annoying flicker when you use minimize and restore on maximized window, which lasts about 1s.

This is with _resize mode_ set to _auto adjust_

I noticed scrollbars are shortly present during restoration and and then removed, which might be cause of this.

**To Reproduce**

1. Maximize window with RDP tab
2. Minimize window
3. Restore window

**Screenshots**
<details><summary>Gif</summary> 

![top2](https://user-images.githubusercontent.com/85767/102723804-0acf6f80-430b-11eb-903a-1afa83e67281.gif)
</details>

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/102750249-76175100-43a0-11eb-8096-29546d980f05.png)

I found AxMsRdpClient9 control auto change its size  when tab window goes to min from max(get bigger) for unknown reason, normal to min will not tiger this issue.
So I stop resize callback when window status change to min until it restore.
