### ISSUE TITLE
Pre connection shell script

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#42]
It would be great to have an option to execute shell script before connecting. 

For example, it could be used to connect to VPN network or change hosts file.

**Comment by VShawn** [comment]
ok, now we need options for

- powershell script before connect
- powershell script after connect (not work for external app who will not notify us when its session is connected e.g. KiTTY）
- powershell script after window close

**Comment by majkinetor** [comment]
Better, one script receiving `$Event` as a parameter.

> powershell script after connect (not work for external app who will not notify us when its session is connected e.g. KiTTY）

Maybe we can make it work even in that case. One thing that comes to mind is setting the kitty title from within kitty script and then looking for it locally as a marker.

**Comment by majkinetor** [comment]
Should this be closed  and part of 0.5.8 milestone ?

**Comment by VShawn** [comment]
I don't know if this can be considered  as complete, now only cmd commands are supported, and only commands executed before connection are supported. That‘s why I didn't close it yet.
