### ISSUE TITLE
Prevent annoying RDP popup 

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#43]
After RDP is retried 5 times popup appears very intrusively.

mRemoteNg prevents this somehow and it can continuously repeat until connection is established.

```
---------------------------
PRemote Info
---------------------------
PIMIS infra(10.111.16.171) : Remote Desktop can't connect to the remote computer for one of these reasons:

1) Remote access to the server is not enabled
2) The remote computer is turned off
3) The remote computer is not available on the network

Make sure the remote computer is turned on and connected to the network, and that remote access is enabled.
---------------------------
OK   
---------------------------
```

**Comment by VShawn** [comment]
i dont think it's a good idea to keep reconnect with out a notification when connection error occurred, 

maybe pop error message after several times auto reconnect failed would be better.


---
BTW, In my refactoring plan, the error message will no longer use the message box to pop up, but will be masked on the RDP display area by a special message prompt layer. when an error occurs, message prompt layer show and you can click a button on it to try to reconnect or close the form.

**Comment by majkinetor** [comment]
> i dont think it's a good idea to keep reconnect with out a notification when connection error occurred,

This could be setup in connection settings, how would you like things handled.

> maybe pop error message after several times auto reconnect failed would be better.

> BTW, In my refactoring plan, the error message will no longer use the message box to pop up, but will be masked on the RDP display area by a special message prompt layer. 

Thats the way to do it, popups are antipattern in general.

**Comment by majkinetor** [comment]
It gets even more annoying - if you have N tabs open on VPN, once you disconnect after few minutes you will get N pop-ups at the same time :)

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/103759073-17afcb00-504e-11eb-808e-1edddc6bf8a6.png)


I change message shown style like above, don't know if it work with your VPN case. could you help to test it?

**Comment by majkinetor** [comment]
sure
