### ISSUE TITLE
Launcher is sometimes stuck in the background and ALT M no longer works

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#49]
Sometimes it isn't even visible.

You should bring window to front on ALT M to fix this.

**Comment by VShawn** [comment]
Yes, I did bring window to front when ALT + M, just no idea why it does not work with you. i never meet this issus.

check:

 
- call Activate()
- Set Topmost to True then False

To make sure it bing window to front work

https://github.com/VShawn/PRemoteM/blob/70c5edec57acbbe36c5f95940471c964b90b8ef8/PRemoteM/View/SearchBoxWindow.xaml.cs#L108-L115

**Comment by majkinetor** [comment]
Its really weird in behavior. Sometimes it is stuck in the back and not visible at all! Sometimes it just stays there even if it has no focus:

![image](https://user-images.githubusercontent.com/85767/103435690-93ef7c00-4c12-11eb-9356-40087bcc08c3.png)

This happens very frequently to me, to the point of making it unusable.

**Comment by majkinetor** [comment]
Its also 100% reproducible.

When the launcher is active, its enough for me to click outside of it (for exmaple desktop). Then it will stay open until you enter it again to see a blinking cursor and press ESC.  If you press at this moment WIN + D to minimize all, its invisible and ALT M doesn't work.

**Comment by VShawn** [comment]
@majkinetor 
I see,I will fix it when i back home, I am in a vocation and travel around now.

**Comment by VShawn** [comment]
it is my fault for commented out the code of auto hide launcher when deactivated for testing purpose, but forgot to change it back. 🐛
