### ISSUE TITLE
Crash when clicking "+"

### ISSUE THREAD

**Issue by Shooshka** [VShawn/PRemoteM#50]
PRemoteM latest at this moment at win10 latest:

![image](https://user-images.githubusercontent.com/1889052/103264235-272e7480-49bb-11eb-94d1-d3cded7feac5.png)
After clicking here got:

![image](https://user-images.githubusercontent.com/1889052/103264253-36adbd80-49bb-11eb-9bff-9adb085c6752.png)

**Comment by VShawn** [comment]
sorry for late reply, but I am in a holiday travel.

attach file is the fix version.

[Release.zip](https://github.com/VShawn/PRemoteM/files/5756165/Release.zip)
