### ISSUE TITLE
add support for password encryption

### ISSUE THREAD

**Issue by SaltyYuki** [VShawn/PRemoteM#51]
**Is your feature request related to a problem? Please describe.**
For security porpose it would be nice to add password encryption

**Describe the solution you'd like**
Add support for password encryption and ask for a password when PRemoteM start

**Describe alternatives you've considered**
add the posiblities to set a password for the RSA private key ?

**Comment by VShawn** [comment]
Hi PRemoteM will not add a  app start password for now.
Here is why:
https://github.com/VShawn/PRemoteM/wiki/password-security


---
BTW, I try to add windows hello biometric security as the protection but few document can be found about.
