### ISSUE TITLE
Password not encrypted when use the multi-edit function

### ISSUE THREAD

**Issue by SaltyYuki** [VShawn/PRemoteM#53]
**Describe the bug**
When I use the multi-edit function to change the password of multiple computers
The new password is not encryted in the database and don't work until I manually click save on every computers

**To Reproduce**
1. Select One or more computer in "Server management"
2. Click on 'Edit Selected' and set the password with a new value
3. The password is not encrypted in the database 

**Expected behavior**
The password is encrypted in the database 

**Desktop (please complete the following information):**
 - OS: [e.g. Win10 Pro 1909]
 - PRemoteM Version [e.g. 0.5.7.2101041110]

**Comment by VShawn** [comment]
Thank you for report, i will fix it soon 😟

**Comment by VShawn** [comment]
hi~ this bug has been fixed: https://github.com/VShawn/PRemoteM/releases/tag/0.5.7.2012240828
please let me know if you have any other issues about PRemoteM
