### ISSUE TITLE
SSH shell issues "=" signs to command line 

### ISSUE THREAD

**Issue by BrommD** [VShawn/PRemoteM#55]
**Describe the bug**
Starting with 0.5.7.2101082141 SSH opened terminals issue "=" chars to CMD line, when not being used for a while (noop effect?). This is happening every few minutes, screenshot below is from a session being opened for 24 hours...

**To Reproduce**
1. open ssh connection to a Linux remore server
2. wait
3.
**Expected behavior**
Not to issue "=" chars to cmd line

**Screenshots**
![image](https://user-images.githubusercontent.com/33422643/104292224-da6b9300-54bc-11eb-9e7b-4e969cdcbaa3.png)

**Desktop (please complete the following information):**
 - OS: Win10 EE 1809 - remote mostly Centos 7/8 Linux
 - PRemoteM Version [0.5.7.2101082141

**Additional context**
I'm using PRemoteM for several month now and switched yesterday to current version by simply replacing all binaries. Before the update, this effect was not happening.

**Comment by VShawn** [comment]
Yes I knew why this happen.
'=' is sent for keep ssh alive bu kitty. it has been annoying  me for a few months after I switch putty to Kitty. 

```
[KiTTY]
adb=yes
; antiidle: character string regularly sent to maintain the connection alive
antiidle== \k08\
; antiidledelay: time delay between two sending
antiidledelay=60
```

**Comment by VShawn** [comment]
Oh God. I know why.

> antiidle== \k08\

should be

> antiidle=\k08\


Ahhh... what a stupid fault 🙀 

fix will comming very soon

**Comment by VShawn** [comment]
fix is available now :  https://github.com/VShawn/PRemoteM/releases/tag/0.5.7.2012240828
so sorry for my stupid act 😰 

Please contact me if you have any question.

**Comment by BrommD** [comment]
Hi

THAT was fast. I appreciate this very. Let me check the result, will report back asap.

Thanks, Dejan

**Comment by BrommD** [comment]
works! thx.

**Comment by VShawn** [comment]
> works! thx.

thx for help improve premotem : )
