### ISSUE TITLE
SSH connection isn't ready for keyboard input upon window focus

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#56]
If you ALT + TAB to another app, then return to ssh connection, you can't type until you explicitly click somewhere in the window. Until you click, cursor is hollow, when you click, it is filed.

**Comment by VShawn** [comment]
actually it's not a bug. 
---

When ssh was implemented by kitty not premotem , so when you back premotem  from alt+tab, you are focus on premotem, so we have to click one time to let kitty get focus.

I made some efforts to let premotem auto focus on Kitty.but anyway extend app will never brings a same experience compare with a native app.

**Comment by majkinetor** [comment]
> actually it's not a bug.

Actually, it is. What you talk about is implementation detail that is irrelevant to end user :) 

> I made some efforts to let premotem auto focus on Kitty. But anyway extend app will never brings a same experience compare with a native app.

Never is a strong word :) We can get creative: you could simulate mouse click when you detect focus on SSH, heck I can even do it externally with AutoHotKey :)

Bug it is.

**Comment by VShawn** [comment]
You may be right, I am more thinking as an engineer than an experience designer. 

But I still think that embedded programs cannot achieve the effects of native programs. Embedded program require additional logic to achieve a same experience with native program, which means it will be more difficult to maintain and more likely to cause bugs, and bring other bad experiences.

**Comment by majkinetor** [comment]
> I am looking for a WPF ssh terminal simulater control and get nothing.

Never mind. Since you plan rewrite I wouldn't lose time on things like this as any solution might be worth nothing when new system is up.

I will see on my own how this can be fixed as it really breaks experience for me (the same was true also for mRemoteNg) and let you know if I find something. You should however keep this in mind when designing new system.

**Comment by VShawn** [comment]
> any solution might be worth nothing when new system is up.

but the purpose of refactoring is only to optimize the structure of the software, and existing solutions may continue to be used.

**Comment by VShawn** [comment]
I tried to fix it, and don’t know if new bugs was introduced.

Try it:
[PRemoteM 0.5.8.2101331121.zip](https://github.com/VShawn/PRemoteM/files/5806680/PRemoteM.0.5.8.2101331121.zip)

**Comment by majkinetor** [comment]
It works if window is alone, however, if I open second tab, then switching between tabs will act the same as before, even a bit worse.


Testing this I discovered a new bug - I open two SSH tabs, and type in one, then in second one I have 2 cursors shown and it can be moved to the right:

![image](https://user-images.githubusercontent.com/85767/104437308-e45dc680-558e-11eb-9f69-10d5a2987da5.png)

**Comment by VShawn** [comment]
>Testing this I discovered a new bug NOT in the previous version - I open two same SSH tabs, and type in one, then in second one I have 2 cursors shown and that cursor can be moved right of its previous location:

Nope, 2 cursors did existed in previous version since I turned PuTTY to KiTTY, I seem them before. 

Just no idea to fix it.

BTW 1 of 2 cursors should disappear after ‘Enter’ or window resize.

**Comment by VShawn** [comment]
another bug was that KiTTY was not killed when the tab was closed.

![image](https://user-images.githubusercontent.com/10143738/104441880-3fafa900-55cf-11eb-8ca8-cd6b2e0f6cf3.png)

**Comment by VShawn** [comment]
> Testing this I discovered a new bug NOT in the previous version - I open two same SSH tabs, and type in one, then in second one I have 2 cursors shown and that cursor can be moved right of its previous location:

I guess the cursor is drawn repeatedly due to multiple activation of KiTTY.

In old version, this bug was easy show up when “auto command” was set.
![image](https://user-images.githubusercontent.com/10143738/104445882-a6839100-55d4-11eb-80f9-9b1a77d50379.png)
