### ISSUE TITLE
Automated build

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#58]
We should have document such as DEVEL.md that should provide reproducible way to setup up local environment.

It should contain machine prerequisites, along with any procedure required to build the app.

**Comment by VShawn** [comment]
I try write a demo:

# Development

PReomteM is written in the [CSharp](https://devblogs.microsoft.com/dotnet/c-9-0-on-the-record/), UI power by WPF.

## Environment
Here is what you need to setup a development environment:

0. [Windows 10](https://www.microsoft.com/en-us/software-download/windows10) 1703 or later
1. [Microsoft Visual Studio 2019 (VS2019)](https://visualstudio.microsoft.com/vs/) Community or higher
2. [.NET Framework 4.8 Dev Pack](https://dotnet.microsoft.com/download/dotnet-framework/net48) (may included in VS2019)
3. (Optional) [ReSharper](https://www.jetbrains.com/resharper/)
4. (Optional) [Git](https://git-scm.com/)

## Build

1. Clone from GitHub.
2. Open PRM solution by VS2019
3. Resotre all NuGet Packages
![image](https://user-images.githubusercontent.com/10143738/104452847-8789fc80-55de-11eb-92f4-2009e344f2eb.png)
4. You can build PReomteM now.

**Comment by majkinetor** [comment]
Thanks. I will move this into its own file on repo and make automated build from CLI.

**Comment by majkinetor** [comment]
> Microsoft Visual Studio 2019 (VS2019) Community or higher

This is not enough and not precise. VS comes with bunch of modules.

This one requires:

- Universal Windows Platform Development

**Comment by majkinetor** [comment]
Looks like even that is not enough.  Reference is still missing on all projects `Windows.X` (PopUp, ApplicationModel, ...).

Old dotNet is horror.

**Comment by VShawn** [comment]
Sorry, I forgot it needs Win10 SDK support.

Here is all I have on my workstation in company (can't find a button for turn VS2019 installer UI into english):

![image](https://user-images.githubusercontent.com/10143738/104528497-6824bb00-5642-11eb-9bc6-0224ade1d0f3.png)
![image](https://user-images.githubusercontent.com/10143738/104528741-06188580-5643-11eb-853c-e601d2646b98.png)
![image](https://user-images.githubusercontent.com/10143738/104528755-116bb100-5643-11eb-847f-6fd58ac25357.png)
![image](https://user-images.githubusercontent.com/10143738/104528760-17fa2880-5643-11eb-9237-fe477addee06.png)


[MY VS2019 install config.zip](https://github.com/VShawn/PRemoteM/files/5811708/MY.VS2019.install.config.zip)

**Comment by majkinetor** [comment]
I managed to build it using the following steps

```ps1
choco install windows-sdk-10-version-1809-all

$lastSdkVersion = Get-ChildItem "${Env:ProgramFiles(x86)}\Windows Kits\10\Include" | Sort-Object -Descending | Select-Object -First 1 -Expand Name

# This is added to PRM.Core and PRemoteM csproj files
"<PropertyGroup>
      <TargetPlatformVersion>${lastVersion}</TargetPlatformVersion>
</PropertyGroup>"

**Comment by majkinetor** [comment]
I keep getting this error when trying to build PRemoteM in SandBox:

`
Unable to write manifest 'obj\Debug\PRemoteM.exe.manifest'. Could not load file or assembly 'System.Data.SqlXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.	PRemoteM			
`

Core builds fine. 

I succeeded to compile it but not sure how, can't reproduce it easily. 

Will look into it some more...

**Comment by majkinetor** [comment]
I pushed this to branch `build`.

What I am trying can be accomplished locally this way:

1. Open admin powershell in root folder of the project
2. Set convenience alias: `Set-Alias ib $pwd\Invoke-Build.ps1`
3. See available tasks with `ib ?`
4. Run `ib BuildInSandbox`

Last command will complain if you don't have sandbox installed and show you command to do it. After that it does this:

1. Opens clean environment
2. Installs ALL prereq using `ib Deps`; takes around 15 minutes
3. It tries to build using CLI commands after that but it will fail (didn't yet look into it, current goal is to build in VS community)

You can now open VS2019 in sandbox and try to build it. Project is available on Desktop.

Those are the deps so far and VS builds it after some interventions.

```
        choco install -y visualstudio2019community
        choco install -y netfx-4.8-devpack
        choco install -y visualstudio2019-workload-manageddesktop
        choco install -y visualstudio2019-workload-universal
```

### What is the point of all this

The point is to have locally reproducible build. This will be used in CI pipeline (on any system, not necessarily GH) instead of magic we have now. Build simply becomes `ib Deps; ib Build` as one step pipeline.

This can also be used to setup dev environment on empty machine.

**Comment by majkinetor** [comment]
BTW, on my own machine `ib Build` worked until it needed to access your private keys for installer.  Build on my machine is not very relevant as I have installed tone of stuff (the same as you as shown by your screenshot, most of which are not relevant to the project).

Here is the error:

```
(_CreateMainPackage target) ->
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(4659,5): error APPX0104: Certificate file 'C:\FastToolsShared\git key\Shawn.pfx' not found. [C:\Work\PRemoteM\Installer\Installer.wapproj]
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Microsoft\VisualStudio\v16.0\AppxPackage\Microsoft.AppXPackage.Targets(4659,5): error APPX0107: The certificate  specified is not valid for signing. For more information about valid certificates, see http://go.microsoft.com/fwlink/?LinkID=241478. [C:\Work\PRemoteM\Installer\Installer.wapproj]
```

notice that your local folder `C:\FastToolsShared\git key\Shawn.pfx` is shown.

**Comment by majkinetor** [comment]
This is how sandbox looks while installing stuff:

![image](https://user-images.githubusercontent.com/85767/104809667-238a5280-57ef-11eb-8aaa-670469d6aaf0.png)

**Comment by majkinetor** [comment]
I think I found the problem:

```
  <PropertyGroup>
    <GenerateManifests>true</GenerateManifests>
  </PropertyGroup>
```

When this is set to `false` SqlXml error is no longer present. This is changed with the following option:

![image](https://user-images.githubusercontent.com/85767/104811447-cba61880-57fb-11eb-9cf7-0121b12eff8f.png)

Since this is problematic, shell we disable it ?

**Comment by majkinetor** [comment]
Can you check if above setting works for you and if so, please commit new PRemoteM.csproj file.

**Comment by majkinetor** [comment]
BTW, the SqlXML assembly is present, and even if I add it among references it changes nothing....

**Comment by majkinetor** [comment]
After this change only your key is problematic from CLI:

`ib Build`

![image](https://user-images.githubusercontent.com/85767/104811746-fee9a700-57fd-11eb-9386-cc978adff66f.png)


![image](https://user-images.githubusercontent.com/85767/104811735-e5485f80-57fd-11eb-9e60-bf6c633398cd.png)

**Comment by majkinetor** [comment]
Found another err, this time in R2Win32 configuration (Debug works fine):

`The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)	PRemoteM	C:\Users\WDAGUtilityAccount\Desktop\PRemoteM\PRemoteM\App.xaml.cs	9	Active`

`The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?)	PRemoteM	C:\Users\WDAGUtilityAccount\Desktop\PRemoteM\PRemoteM\ViewModel\VmServerListPage.cs	12	Active`

Those are easily fixed using VS option _Remove and sort usings_ in 2 mentioned files, then `ib Build -aReleaseType R2Win32` works. Not sure how and why unused usings influence build, but there you go....

**Comment by majkinetor** [comment]
So, to recap all above :-)

1. Remove unused usings in `App.xaml.cs` and `ViewModel\VmServerListPage.cs`
2. Remove click once options in PRemoteM.csproj and remove dummy manifest from csproj or just add it again.
3. Remove or fix installer project so that it doesn't require your private keys.

**Comment by VShawn** [comment]
wow a lot of great job...

## 1. Remove unused usings in App.xaml.cs and ViewModel\VmServerListPage.cs
> The type or namespace name 'Windows' could not be found (are you missing a using directive or an assembly reference?) PRemoteM C:\Users\WDAGUtilityAccount\Desktop\PRemoteM\PRemoteM\ViewModel\VmServerListPage.cs 12 Active

but using System.Windows is do needed in VmServerListPage.cs App.xaml.cs, and I dont think the unused usings will cause this build problem.

BTW here is what unused using

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/10143738/104829972-7da11b80-58b4-11eb-9807-9d081e27e0a2.png)

![image](https://user-images.githubusercontent.com/10143738/104829982-a2958e80-58b4-11eb-88bd-8c2865862a77.png)

</details>


## 2. Remove click once options in PRemoteM.csproj and remove dummy manifest from csproj or just add it again.

> click once options

I dont even know when I enable it :(, And I find it would be useless in PRM according to [wiki](https://en.wikipedia.org/wiki/ClickOnce) since we publish release by 7z package and Microsoft store. I will get it disabled

> manifest 
[WIP] I have to go out now, check it latter. 

But I have no impression of this file as well, it may be used in Microsoft store for diagnostic purpose. Check app.manifest by a quick view, finding it generated by Microsoft store automatically and nothing secret in it, since git ignor it for unknown reason I may push it manually


## 3. Remove or fix installer project so that it doesn't require your local certificate.

certificate is required so that it can publish to microsoft store, do you know how any approch for microsoft store package build into CI?

OR we can add a dummy certificate  for CI build to sign msix, push it to git, with it CI can build a msix that can be insatlled only if the user install the dummy certification, check: https://www.advancedinstaller.com/install-test-certificate-from-msix.html

OR we may **ignor the build msix package in CI**, CI will only offering the WIn32 exe release.

**Comment by majkinetor** [comment]
> but using System.Windows is do needed in VmServerListPage.cs

That one that got remove are Windows.Application.Store, System.Windows.Data, System.ComponentModel, System.Diagnostics.

>and I dont think the unused usings will cause this build problem.

I am not sure what is going on here, but that action solved it for me and since its repeatable, you can try it on your own. I noticed once for that error that it was enough to just hover with mouse over the error line, and the error would disappear after that ?! Didn't analyze it more.


> But I have no impression of this file as well

When you deselect click once, it is added automatically by VS in csproj, but not in file system

> certificate is required so that it can publish to microsoft store, do you know how any approch for microsoft store package build into CI?

> OR we may ignore the build msix package in CI, CI will only offering the WIn32 exe release.

I am up for that one as I personally think almost nobody will use this from Store (maybe I am wrong, but the target audience for store are not IT professionals).

OK, let me try to ignore it in CI until we have a way to use secrets vault.

BTW, Installing and starting a sandbox on your local machine should be trivial, you should check it out yourself. I will ofc document everything once its done but If you need any more  info now let me know.

**Comment by VShawn** [comment]
> Installing and starting a sandbox on your local machine should be trivial

Nope, in facte It is quite difficult for me since we have a [powerful firewall](https://en.wikipedia.org/wiki/Great_Firewall) that make me a hard way to connect to the international networks.

![image](https://user-images.githubusercontent.com/10143738/104867611-3ed69880-597c-11eb-9182-a3758362f313.png)

> I personally think almost nobody will use this from Store

Over 300 downloads from Store since 2020.12.01, impressive

**Comment by majkinetor** [comment]
> Nope, in facte It is quite difficult for me since we have a powerful firewall that make me a hard way to connect to the international networks.

God damn... I'll think of something... if possible.

> Over 300 downloads from Store since 2020.12.01, impressive

OK, I stand corrected :)


BTW, did you disable the manifest ? I see you removed unused usings.

**Comment by VShawn** [comment]
I uploaded app.manifest, did it can be treated as fixed?

https://github.com/VShawn/PRemoteM/blob/dev/PRemoteM/Properties/app.manifest

**Comment by majkinetor** [comment]
I just checked, and now it builds in VS2019 community without problems in Debug mode. In Win32 mode there is an erorror:

![image](https://user-images.githubusercontent.com/85767/104903902-ddfd8f00-5980-11eb-918d-6cb936da1844.png)

I committed a fix now on `dev` branch, and now it works up to the problem with keys which remains to be fixed.

Here is a transcript: [build.log](https://github.com/VShawn/PRemoteM/files/5829615/build.log)

**Comment by majkinetor** [comment]
OK, so this is easily fixed by excluding it from the build in that configuration:

![image](https://user-images.githubusercontent.com/85767/104905900-477e9d00-5983-11eb-87bf-938a06ad7c89.png)

It builds OK from the CLI after that and it shows that it doesn't build installer:

![image](https://user-images.githubusercontent.com/85767/104906054-7a289580-5983-11eb-9598-fa47b4c7f159.png)

I committed a change to SLN file to `dev`.

**Comment by majkinetor** [comment]
So, all issues are now solved except automation of Store build but that is for some other topic. 

Now I need see how/where to host this, and to avoid provisioning each time as it takes 15-20 minutes to install all, and there is that firewall thingy...

**Comment by VShawn** [comment]
congratulations 👍 , it finally works.

Interop.MSTSCLib.dll
AxInterop.MSTSCLib.dll

this two libs is needed by RDP, genertaed by windows. All apps that support RDB need them.
https://github.com/mRemoteNG/mRemoteNG/blob/2cf5a4317d0cbd61c2135aa8f7ab608db2d88629/mRemoteNGInstaller/Installer/Fragments/FilesFragment.wxs#L40

**Comment by majkinetor** [comment]
That is strange.... I don't have those 2 files in my build for some reason. 

I tested RDP in Sandbox and it works without them! I searched entire sandbox drive for them and they are not there.
