### ISSUE TITLE
Add protocol: RemoteApp

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#60]
RemoteApp and Desktop Connections is a new feature in Windows 7 and Windows Server 2008 R2 that builds on this by bringing RemoteApp programs to the Start menu, giving them the same launch experience as local applications.

[x] Add protocol implement
[x] Write a simple how to use: https://github.com/VShawn/PRemoteM/wiki/RemoteApp-program

**Comment by majkinetor** [comment]
I didn't know this is possible. I tried remoteapp now and it works great.

One of the points of remote app is to be able to see them as standalone apps on taskbar. This might deserve a new display option in PRM, such as _Use separate Window and taskbar icon_

**Comment by majkinetor** [comment]
It works nice.

One thing is troubling me tho - my blue tooth connection to speakers is imediatelly terminated when I connect to remote app (via premotem and rdp file). This doesn't happen with desktop connections...

**Comment by majkinetor** [comment]
RemoteApp protocol on icon is a mess:

![image](https://user-images.githubusercontent.com/85767/104817344-f3f43e00-5820-11eb-95a5-bf7d871bc625.png)


Perhaps:

- It should be listed on top of icon
- Protocols could have different backgrounds, that is much easier to identify what is what. I discussed protocol configuration idea earlier (#59) and if we go that route, it could be specified there.
- It could just be called _App_ instead _RemoteApp_ or _RApp_

**Comment by VShawn** [comment]
> One thing is troubling me tho - my blue tooth connection to speakers is imediatelly terminated when I connect to remote app (via premotem and rdp file). This doesn't happen with desktop connections...

Curious why. Did this problem happen to a .rep file build by remoteapp tool too?

> Protocols could have different backgrounds

Did we real need a background to identify what property it is? I personally don’t pay any attention to its property when I need connect to a server. 

> It could just be called App instead RemoteApp or RApp

I tried named it as ‘App‘ before, and the protocol name will changed. It is a insufficient data structure design, I design to fix it later.

![image](https://user-images.githubusercontent.com/10143738/104829200-74ac4c00-58ac-11eb-9568-57061036d853.png)

**Comment by majkinetor** [comment]
> Did this problem happen to a .rep file build by remoteapp tool too?

Yes.
