### ISSUE TITLE
Connection option to specify kitty profile 

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#68]
Kitty/putty has a profile given the huge number of options it has. PRM should support specifying it.

If existing profiles can be listed even better, but it would be enough to just specify it by name.

One should keep in mind that this couples PRM with local system settings and if it is moved to another machine connection may not work. There might be a way to embed the profile in PRM connection settings.

**Comment by VShawn** [comment]
@bluikko

Do you mean this setting?
![image](https://user-images.githubusercontent.com/10143738/106139643-a674bb00-61a8-11eb-9792-9192f91deb06.png)

let me think about it 
there are several sources:

- putty profile in register table
- kitty profile in register table
- kitty-portable profile in files

they are in different format, it is a challenge to list them together.

**Comment by bluikko** [comment]
Yes that is the setting.

I would say forget about kitty, not everyone can or want to use it.

**Comment by majkinetor** [comment]
> I would say forget about kitty, not everyone can or want to use it.

Kitty is the only one that supports advanced options, such as sending password, so I guess that is not an option.

**Comment by bluikko** [comment]
I've not missed any kitty options - not sure what they are exactly. Sending password would not be helpful in an enterprise where password saving is forbidden.

Using a SSH agent is a far better solution. Typing a password for those devices that do not support public keys in a directory service (switches etc. mostly) is not a big thing compared to the security benefits.

It seems you target home users. Just trying to give an enterprise point of view.

**Comment by majkinetor** [comment]
> not sure what they are exactly.

Thats why you didn't miss them :)

> Sending password would not be helpful in an enterprise where password saving is forbidden.

Even enterprise does that on production envs, while devs typically handle dozen of stage/test/whatever environments that don't have such requirements.

> Using a SSH agent is a far better solution

You have `before cmd` now so you can use it to start agent.

> It seems you target home users.

While I do think that @VShawn targets home users (mostly due to _Personal_ in PRM), I think it should work for enterprise users. I used number of 'enterprise' tools like this and ditched them all.

**Comment by bluikko** [comment]
I brought up the SSH agent because profiles were not supported - mine is started on Windows startup.

We have to just agree to disagree. I hope nobody would use a plain password on those environments, I'd expect them to use keys and likely with an agent.

**Comment by majkinetor** [comment]
> I hope nobody would use a plain password on those environments

OK, lets disagree then :) I would demand against it on my projects, because that would slow everybody down a lot for no good reason (on test environments data is mostly generated). So you are the one for the form, I am the one for the customer satisfaction (which is low if you are slow).

**Comment by VShawn** [comment]
> I would say forget about kitty, not everyone can or want to use it.
 
I change to Kitty just because It support auto-command, to let me auto run some compile or test when I connect to a VM Ubuntu.

It should be selectable for user to choose SSH via KiTTY/PuTTY/[PuTTY-CAC](https://github.com/NoMoreFood/putty-cac) in the future version. Then you may choose what you like. But now we still a long trip to achieve this above #61.

> Just trying to give an enterprise point of view.

I did build PRM for home users. Since all my test were based on VMs, no IT supports makes me hard to test something like RDP Gateway / SSH agent / SSH tunnels( i.e. I can add the feature but can't test it), if I can build the environment one day, I'd like to add support them.

BTW It is wellcomed for someone enterprise user to add new key support for PRM. PRM is not limit to `persional` only.
