### ISSUE TITLE
Redesign of unhandled error form

### ISSUE THREAD

**Issue by VShawn** [VShawn/PRemoteM#69]
it is ugly and un-fridenly alert when unhandled error occurred.

like #67 
![image](https://user-images.githubusercontent.com/17590539/105962418-77ffbe80-6088-11eb-834d-e14f763b34b5.png)

we need a new form to handle this

- a new form to show unhandled error
- allow user copy error info
- hyperlink to GitHub issues to report error.
- email link for those people dont use github.

**Comment by majkinetor** [comment]
> allow user copy error info

This is usually OS system function, use ctrl + c, but it could be handy to have explicit copy to clipboard button.

**Comment by majkinetor** [comment]
Error info should include full stack trace.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/106379289-d8269580-63e5-11eb-9758-8e8fd45dace3.png)

this is how the form would like

**Comment by VShawn** [comment]
this one would be better 

![image](https://user-images.githubusercontent.com/10143738/106379681-96e3b500-63e8-11eb-94b5-513f2f715e0c.png)

**Comment by majkinetor** [comment]
Looks good.

Some wording fixes:

1. Unexpected error occurred. Error info is shown bellow:
2. Please help us improve PRemoteM by reporting this error
3. Simply copy the error message and choose one of the ways to report it
4. Send by e-mail
5. Send by GitHub
6. Copy to clipboard

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/106434075-05d61200-64ac-11eb-84f4-f726aa60efdf.png)

done. 
works on my company win10.

**Comment by majkinetor** [comment]
You might want to improve on markdown

- add bullet points to environment info 
- add stacktrace to code blocks

**Comment by VShawn** [comment]
There would two formats for log dump. 

- on UI log can be in txt format for good looking.
- If user copy / save it to file, log would be save as markdown text.

IMO none empty line in the textbox is for reader-friendly( too manay empty line lead low information density)
