### ISSUE TITLE
Inconsistent release and tag name

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#75]
![image](https://user-images.githubusercontent.com/85767/106622535-fa4e1e00-6573-11eb-970b-116b3d1bd376.png)

This also shows as wrong update info:

![image](https://user-images.githubusercontent.com/85767/106622660-1ce03700-6574-11eb-9eef-e94b74ead261.png)

On choco tag name is taken as version:

![image](https://user-images.githubusercontent.com/85767/106622727-2f5a7080-6574-11eb-8c80-984e6b8b11c8.png)

**Comment by VShawn** [comment]
That's because I overwirte the old release using a hotfix relase for bug fix for convenience. Next time I will pay attention to create a new tag.

**Comment by majkinetor** [comment]
Oh, that is antipattern, never overwrite a release :).

You can always release a hotfix as a pre-release. I hope to get some time soon to automate releasing then it will be most convenient.
