### ISSUE TITLE
Sound stops working on remote machine

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#81]
**Describe the bug**
I set up connection to my media center on Windows and as soon as I connect sound stops working.

<details><summary>The connection settings</summary>

![image](https://user-images.githubusercontent.com/85767/107262598-05f08780-6a41-11eb-97f9-16474e84e248.png)</details>

<details><summary>The native RD seting </summary>

![image](https://user-images.githubusercontent.com/85767/107262718-2ddfeb00-6a41-11eb-81aa-8884484e5010.png)</details>

It looks like PRM has only 2 settings (play on host/do not play) while it needs 3.

**Expected behavior**
The sound shouldn't stop playing on remote machine, just like it doesn't do on native RD when above option is set.

**Desktop (please complete the following information):**
 - OS: Win10 10.0.19042
 - PRemoteM Version 0.5.8.2101192131

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/108346581-802bc380-721a-11eb-88df-5d6fe21a9227.png)

this might fix only if we set line 158 to "1", no new options needs to add.

**Comment by majkinetor** [comment]
> Is this ambiguous in your opinion? text will get cut off if I wrote whole statement "Play on remote computer"

Why not using single combobox and add 3 options ? That will solve your current interface and translation problems

```
Sound: [ disable, local, remote ]
```

unless its possible to play both local and remote (I 99% sure it isn't)

> this might fix only if we set line 158 to "1", no new options needs to add.

That solution is semantically incorrect - you can't enable sound in branch that should be run if sound is disabled :) Go with the combo IMO. Its equiv to RDP native radio group but its way easier and non problematic in visual aspects.


<details><summary>FYI @VShawn </summary>

You can also link to the file directly instead of using screenshot, like this:

https://github.com/VShawn/PRemoteM/blob/1cfa90ec43b5a58076490157c5f82e806ba902eb/PRM.Core/Protocol/RDP/Host/AxMsRdpClient09Host.xaml.cs#L143-L159

</details>

**Comment by VShawn** [comment]
>  Go with the combo IMO

ok... do it latter


> You can also link to the file directly instead of using screenshot, like this

I knew, just lazy to find the file on GitHub :sweat:

**Comment by majkinetor** [comment]
> I knew, just lazy to find the file on GitHub 😓

I supposed that, and its OK. Perhaps you missed also that [Go to file](https://github.com/VShawn/PRemoteM/find/dev) lets you do that by typing couple of letters... in this case `axh` :)

**Comment by VShawn** [comment]
it works 

![image](https://user-images.githubusercontent.com/10143738/108486989-b2e8c100-72d9-11eb-873f-92afb0883674.png)

>  Perhaps you missed that Go to file lets you do that by typing couple of letters

thanks for the tip!
