### ISSUE TITLE
RDP connection to Win Server 2008 R2 reconnects by itself after logging out from the remote server.

### ISSUE THREAD

**Issue by NAV-Management** [VShawn/PRemoteM#82]
**Describe the bug**
If you have an RDP connection open to a Windows Server 2008 R2 and and log out of the server via Start Menu -> Logout, you will be logged in again immediately.

<details><summary>Screenshots</summary>

![RDP Win 2008 R2](https://user-images.githubusercontent.com/24463981/108288831-93448200-718d-11eb-9398-9d8da1b43b00.gif)
</details>

**Desktop (please complete the following information):**
 - OS: Connecting from Windows Server 2019 to 2008 R2
 - PRemoteM Version: PRemoteM.0.5.8.2101282043

**Comment by VShawn** [comment]
I found I dont have a 2008 server. install a new in VirtualBox right now!

**Comment by VShawn** [comment]
interesting

win2008 reply 'NoInfo' when log out from server.
while win10/win2016 reply 'exDiscReasonLogoffByUser‘ when user log out

![image](https://user-images.githubusercontent.com/10143738/108355689-1e715680-7226-11eb-8cbd-83e1ce26bf1b.png)

PRM find it not the specified disconnected reason and then try reconn to server.
