### ISSUE TITLE
Bulk editing all attributes of selected connections

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#83]
Idea in nutshell is:

1. Add multiselect options and some more advanced filtering
2. Allow using group actions on selection: Еdit all, Delete all, Connect all (edit explained further)
3. Show the same edit window as we have it now with following changes:
    1. In multi edit mode warning is shown with number of connections it is applying to
    2. When all connections have the same value it is shown, if not, some special value is shown such as `<multiple values>` or  `<unchanged>`
    3. There is again warning on save , just to be sure you saw it.
4. "Server management" should be removed along with special multi edit items in the footer (edit selected, back etc.)
5. "Edit selected property" should be removed

One decision should be made: if group edit is allowed with multiple protocols or not. I don't think its much of a hassle to implement any of it, but single protocol may be a bit easier.

Some benefits of this approach are:

1. Group and single edit are basically the same, so no learning or surprises, its intuitive
2. There are no new interfaces to learn (those removed)
3. Its maintainable - changing connection edit window automatically changes group edit unlike current option.

<details><summary>Screen mockups</summary>

![view](https://user-images.githubusercontent.com/85767/113744751-46991400-9705-11eb-84e2-fea6a3726c80.png)

![view_selected](https://user-images.githubusercontent.com/85767/113744767-4a2c9b00-9705-11eb-89f7-68de2b608983.png)

![group_edit](https://user-images.githubusercontent.com/85767/113744806-531d6c80-9705-11eb-8271-31242a1b0046.png)

![view_cards](https://user-images.githubusercontent.com/85767/113744819-56b0f380-9705-11eb-957a-be12f15b5d03.png)

</details>
---

[From discussion at #34](https://github.com/VShawn/PRemoteM/issues/34#issuecomment-780906751)

**Comment by majkinetor** [comment]
@VShawn , check out description for how I thought this could work.

**Comment by VShawn** [comment]
For reference, this is the launcher multi-choice scheme I designed last year for clipboard manager demo by <kbd>←</kbd> key.

![1](https://user-images.githubusercontent.com/10143738/114017026-16d14400-989e-11eb-98ba-40765c3ce0f1.gif)


just... unfortunately, I don’t have time for PRM recently.

**Comment by VShawn** [comment]
WIP

**Comment by VShawn** [comment]
Complete most of the UI changes on  list page 

![image](https://user-images.githubusercontent.com/10143738/117652018-3d4c0d00-b1c5-11eb-9984-043c1e3bb841.png)

**Comment by majkinetor** [comment]
Nice, looking forward to test that.

Keep in mind that both UI's (panes vs list) should in principle have the same options.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/117813414-a0a57000-b295-11eb-9569-6d03c2d0b970.png)

a little bit of progress by huge code re-factoring

**Comment by VShawn** [comment]
Done most of the work, The radio button needs to be replaced with combobox in the next step

![1](https://user-images.githubusercontent.com/10143738/118355311-e0c06780-b5a1-11eb-9634-7b3ea53f7ddd.gif)

@majkinetor  try it
[PRemoteM 0.5.10.3-beta3.zip](https://github.com/VShawn/PRemoteM/files/6484942/PRemoteM.0.5.10.3-beta3.zip)

**Comment by majkinetor** [comment]
Works great, didn't find any issues.

**Comment by majkinetor** [comment]
About missing things: 

1. Number of selected items
    1. In the list, somewhere around footer buttons
    2. In config editor as a header or footer so you know you are not modifying single one
2. Improved search so bulk editing items are easier to form (for example single protocol, server etc.).

**Comment by majkinetor** [comment]
Found few things:

1. Cancel button doesn't work
2. You can't delete connection in list view

**Comment by VShawn** [comment]
which cancel button? 

![image](https://user-images.githubusercontent.com/10143738/118358412-351f1380-b5b1-11eb-9dfc-6823d772df6f.png)
 ↑ I‘ve tested this button several times

**Comment by majkinetor** [comment]
Cancel that shows on the list when you select multiple items

**Comment by VShawn** [comment]
> Cancel that shows on the list when you select multiple items
Yes I forgot that button. 😆

**Comment by VShawn** [comment]
I think we've all done this

[Release.zip](https://github.com/VShawn/PRemoteM/files/6492988/Release.zip)

**Comment by majkinetor** [comment]
Cant see that _Select 2 items_ although I see you are editing in bulk. I would make it more visually distinct tho, I would never notice it if I didn't see screenshot. BTW, make it `Number of selected items: <N>` as that english is wrong and suffers from 1/many grammar problem.

---

With this major feature done, I would suggest doing #107 next - the bulk connect is awesome but it has 1 big problem - you can't save arbitrary connection lists for bulk connection since connection can have only one group, and you also probably want to group connection based on something else then bulk connecting. 

Example: I have 2 database servers on a project along with N other connections. Group name is the name of the project, but I want to connect to db servers only, not anything else. Currently I have to always select db connections then bulk connect. With tags, I could create arbitrary connection lists and bulk connect to them with appropriate UI.

**Comment by VShawn** [comment]
> Number of selected items: <N> 

got it

> #107 next

sure I came here from #107, but I‘m still hesitating whether to add a tag system.

**Comment by VShawn** [comment]
![image](https://user-images.githubusercontent.com/10143738/118604726-148cce80-b7e8-11eb-8363-e7c25627d140.png)

this should be conspicuous enough

**Comment by VShawn** [comment]
[0.5.10.3 beta.zip](https://github.com/VShawn/PRemoteM/files/6515436/0.5.10.3.beta.zip)
