### ISSUE TITLE
Chinese sentences in error info / ORM library

### ISSUE THREAD

**Issue by majkinetor** [VShawn/PRemoteM#88]
English should be the only allowed language in entire project.

```
## Error Info
【主库】状态不可用，等待后台检查程序恢复方可使用。连接字符串错误，或者检查项目属性 > 生成 > 目标平台：x86 | x64
```

Mentioned on #85, this is due to FreeSql ORM

https://github.com/dotnetcore/FreeSql/blob/c12c5523525818abaa05b03d2dfd6ae70b6e7964/Providers/FreeSql.Provider.Sqlite/SqliteAdo/SqliteConnectionPool.cs#L193

**Comment by majkinetor** [comment]
Daper is minimal ORM: https://stackexchange.github.io/Dapper/

We tested it extensively and it works great with only around 20% slowdown. There are few [limitations](https://docs.microsoft.com/en-us/dotnet/standard/data/sqlite/dapper-limitations) but nothing serious and it obviously is recommended by MS.

**Comment by VShawn** [comment]
question, can Daper auto update table structure when I add new properties to the model.

freesql can auto sync structure when the model change.

https://github.com/VShawn/PRemoteM/blob/a64edac60627a21abc993f4918289982dbb7e8cf/PRM.Core/DB/freesql/FreeSqlDb.cs#L75-L80

**Comment by majkinetor** [comment]
As far as I know, no. 

In my projects we use entity framework only for that  (just DDL, not even seeding data, Powershell does that) and dapper for everything else, we and also do it externally. Entity can autodoit via the code similar to what you show. We have a db model project that the main project depends on for models and create and apply db migrations within it with one command. Making this work OTB is like ... 10 minutes work ? We also use it to reset migrations later. Devs can then use it fom VS itself or via CLI.  Here is entire CLI code for that for example <details>
![image](https://user-images.githubusercontent.com/85767/109378766-fcad4a80-7889-11eb-9c5f-e18bb4e96771.png)
</details>

Like I said, dapper is minimal ORM with performance in mind and doesn't have all bells and whistles.  This is not database heavy project, quite contrary. I don't think that is a deal breaker and you can go with proposed alternative that will not bloat main project if you want to go that route.

**Comment by majkinetor** [comment]
Nice, I see u are using dapper now :)

This is [nice info](https://stackexchange.com/performance) :)
