### ISSUE TITLE
Integrate German Language from my Fork

### ISSUE THREAD

**Issue by NAV-Management** [VShawn/PRemoteM#92]
Hello @VShawn,

could you please integrate the german language which I added in my fork?

These 2 Files are needed:
https://github.com/NAV-Management/PRemoteM/blob/dev/PRM.Core/Languages/de-de.json
https://github.com/NAV-Management/PRemoteM/blob/dev/PRM.Core/Languages/de-de.xaml

I changed this file to make it selectable and is needed as well:
https://github.com/NAV-Management/PRemoteM/blob/dev/PRM.Core/Model/SystemConfig.Language.cs

Lines 73 to 79 are added and line 104

On my side I didn't know how to make an pull request from my fork and I did some stupid things so it's easier to just include the 3 files.

I think it must be on the latest language version, because I added the 3 Properties for the sound (sound_disabled, play on local, play on remote).

**Comment by VShawn** [comment]
Thank you fro your  translation, I merged it into my dev branch. 🤝 

and wiki has been updated: https://github.com/VShawn/PRemoteM/wiki/Help-wanted:-Translation
