### ISSUE TITLE
Middle Mousebutton functions

### ISSUE THREAD

**Issue by NAV-Management** [VShawn/PRemoteM#93]
In modern browsers you can use the middle mouse button on the tab to close it.
It would be very nice to have this for the RDP tool as well :).

Another feature I would suggest is that when you middle click on an item in the main menu, it opens in the background, so you can open multiple RDP sessions from the main menu and when you are done, you switch to the rdp window with all connected.

What do you think about this?

**Comment by VShawn** [comment]
In modern browsers, middle click the can close tab only if it is in the background. Nothing happen when I middle click the activated tab.

We can follow this approch.


Open in background  sounds interesting. We can achieve the same `background-open` in the launcher by <kbd>Ctrl</kbd> + <kbd>Enter</kbd>

**Comment by NAV-Management** [comment]
You can close with middle mouse button on active and inactive tab. It's just a bigger close button ;).
![Middle Mouse Button](https://user-images.githubusercontent.com/24463981/109658641-1dfe8700-7b67-11eb-9b7c-174b63982369.gif)
