### ISSUE TITLE
unhandled Error when connecting, if port is defined in both, Address Field and Port Field

### ISSUE THREAD

**Issue by Aufstandsboxer** [VShawn/PRemoteM#97]
**Description**
I copied a rdp-shortcuts data (address incl. Port) straight into the address field of a new PRemoteM-Connection-Element and tried to connect. Got an Error like
"Value does not fall within the expected range." (see screenshot 1)

**To Reproduce**
1. Create new rdp Connection
2. Add a Port to the Address-Field, as well as the Port-Field (see screenshot 2)
3. Save the connection and try to connect

**Expected behavior**
Either a Warning or Input-Error when specifiyng the Port in the wrong field or a proper handling of the error when connecting.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/58400388/111514159-c14bc080-8751-11eb-98db-1533414a31ee.png)
![grafik](https://user-images.githubusercontent.com/58400388/111514609-30c1b000-8752-11eb-8e5c-c835b8b59792.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - PRemoteM Version 0.5.8.2101282043

**Additional context**
low prio from my pov

**Comment by VShawn** [comment]
Thanks for reporting the issue.

I knew the best solution it to prevent uset input error address , but I fix this by `try ... catch` as a quick fix.
