### ISSUE TITLE
Wrong program signature! The program is irremediably altered. Download a new version from official web site."

### ISSUE THREAD

**Issue by Josephkready** [VShawn/PRemoteM#98]
**Describe the bug**
When I add an ssh connection, and try to get connect I get the following popup:

"Wrong program signature! The program is irremediably altered. Download a new version from official web site."

If I press okay, it just closes the window. I have confirmed the ssh sessions work through powershell. 

I installed the app from the windows store. The RDP connections work fine. I havne't tried the others yet. 

**To Reproduce**
1. Download app from windows store
2. Add a ssh connection
3. Launch the ssh connection

**Expected behavior**
Successful connection to the computer through ssh

**Screenshots**
![image](https://user-images.githubusercontent.com/46139224/112353220-8a1d6800-8c99-11eb-8398-eedb0c285ee8.png)

**Desktop (please complete the following information):**
 - OS: e.g. Win10 Pro 20h2
 - PRemoteM Version 0.5.9.2102191952

**Additional context**
bwt I love what you have built! Having an RDP manager that works with multiple monitors has been a huge pain to find. I tried them all!  Your sweet project does it and I am very thankful!! I'll be sending some coffee your way 😉

**Comment by VShawn** [comment]
Thanks for report. This alert is reported by the KiTTY, I don't know what happen so far. Can you send me a sample KiTTY of your `C:\Users\YOUR NAME\AppData\Roaming\PRemoteM\Kitty\kitty_portable_PRemoteM.exe`?

**Comment by Josephkready** [comment]
My folder at C:\Users\{user}\AppData\Roaming\PRemoteM is empty. Maybe that has something to do with it?

**Comment by VShawn** [comment]
> My folder at C:\Users{user}\AppData\Roaming\PRemoteM is empty. Maybe that has something to do with it?

No, if `kitty_portable_PRemoteM.exe` is not existed, the alert would not appear and PRM should alert you that it can't create the folder. So `kitty_portable_PRemoteM.exe` must be somewhere in your PC. maybe you can search it out:

![image](https://user-images.githubusercontent.com/10143738/112473732-b1fbf100-8da9-11eb-9295-c069cd0d2087.png)


BTW, since the new 0.5.10 was released, you can try the new version first.

**Comment by Josephkready** [comment]
I installed the new 0.5.10 version by downloading the zip and running the exe file inside. If I create a ssh connection using ssh V2 I get this screen but can't type or anything. 
![image](https://user-images.githubusercontent.com/46139224/112475491-dc649480-8d3e-11eb-9dfc-697d75057066.png)
Eventually it will show this error: 
![image](https://user-images.githubusercontent.com/46139224/112475829-3cf3d180-8d3f-11eb-8dce-382cd53c3ae3.png)


If I choose v1, I get this error: 
![image](https://user-images.githubusercontent.com/46139224/112475538-ea1a1a00-8d3e-11eb-81c6-df9167e093c6.png)

After installing the new version, I now have the kitty_portable file in my Appdata. I am able to manually open kitty and successfully connect to my ssh target. I did try deleting the kitty file, but I get the same 'Network error' as above when reconnecting through PRemoteM.

**Comment by VShawn** [comment]
@Josephkready 
can you send a screenshot of your ssh config page?

BTW, This works for me
![image](https://user-images.githubusercontent.com/10143738/112476960-68150a00-8dad-11eb-8dff-f18d18703ada.png)

**Comment by VShawn** [comment]
change prot from 3389 to 22, issue fix

**Comment by cjdxhjj** [comment]
i'm install via windows store, the folder C:\Users{user}\AppData\Roaming\PRemoteM is not exist
